@extends('layouts.platform')
@section('content')
<header class="platform-page-header"><div><span class="ui-badge ui-badge--warning">Lodgix support mode · read only</span><h1 style="margin-top:10px">Operational workspace</h1><p>{{ $session->organization?->name }} · {{ $session->property?->name ?: 'Organization metadata only' }}</p></div><form method="POST" action="{{ route('platform.support.end') }}">@csrf<button class="ui-button ui-button--warning" type="submit">Exit support mode</button></form></header>
@include('platform.support.workspace._nav')
<div class="platform-note platform-danger-note" style="margin-bottom:18px"><strong>Platform Administrator · read only.</strong> The support context is derived from the active audited session. Customer authentication, membership and normal property switching are not used.</div>
@if($data['organizationOnly'])<section class="platform-card"><div class="platform-empty"><strong>Organization-level metadata support</strong><span>Select a property when starting support to inspect operational records.</span></div></section>@else
<section class="platform-kpis">@foreach([['Reservations','reservations'],['Clients','clients'],['Rooms','rooms'],['Open tasks','open_tasks']] as [$label,$key])<article class="platform-kpi"><div class="platform-kpi__label">{{ $label }}</div><div class="platform-kpi__value">{{ number_format($data['metrics'][$key]) }}</div><div class="platform-kpi__hint">Scoped to this support property</div></article>@endforeach</section>
<section class="platform-card"><header class="platform-card__header"><div><h2>Recent reservations</h2><p>Read-only operational records for the selected property.</p></div><a class="ui-button ui-button--secondary ui-button--compact" href="{{ route('platform.support.workspace.module', [$session, 'reservations']) }}">View all</a></header><div class="platform-table-wrap"><table class="platform-table"><thead><tr><th>Code</th><th>Guest</th><th>Room</th><th>Stay</th><th>Status</th></tr></thead><tbody>@forelse($data['recentReservations'] as $reservation)<tr><td><a class="text-link" href="{{ route('platform.support.workspace.detail', [$session, 'reservations', $reservation->id]) }}">{{ $reservation->code }}</a></td><td>{{ $reservation->client?->full_name }}</td><td>{{ $reservation->room?->room_number ?: '—' }}</td><td>{{ $reservation->check_in?->format('Y-m-d') }} → {{ $reservation->check_out?->format('Y-m-d') }}</td><td>{{ $reservation->status?->value ?? $reservation->status }}</td></tr>@empty<tr><td colspan="5"><div class="platform-empty"><strong>No reservations in this property.</strong></div></td></tr>@endforelse</tbody></table></div></section>
@endif
@endsection
