@extends('layouts.platform')
@section('content')
<header class="platform-page-header"><div><h1>Support access</h1><p>Start a visible, time-bounded, read-only support session for one customer context.</p></div></header>
<div class="platform-grid">
    <section class="platform-card"><header class="platform-card__header"><div><h2>Start support mode</h2><p>Reason and expiry are mandatory. This does not impersonate a customer.</p></div></header><div class="platform-card__body">
        <form method="POST" action="{{ route('platform.support.start') }}">
            @csrf
            <div class="platform-form-grid">
                <div class="form-field"><label class="form-label" for="organization_id">Organization</label><select class="form-control" id="organization_id" name="organization_id" required><option value="">Select organization</option>@foreach($organizations as $organization)<option value="{{ $organization->id }}">{{ $organization->name }}</option>@endforeach</select></div>
                <div class="form-field"><label class="form-label" for="property_id">Property (optional)</label><select class="form-control" id="property_id" name="property_id"><option value="">All organization metadata</option>@foreach($organizations as $organization)<optgroup label="{{ $organization->name }}">@foreach($organization->properties as $property)<option value="{{ $property->id }}">{{ $property->name }}</option>@endforeach</optgroup>@endforeach</select></div>
                <div class="form-field form-field--full"><label class="form-label" for="reason">Reason</label><textarea class="form-control" id="reason" name="reason" rows="4" minlength="10" maxlength="1000" required placeholder="Explain why support access is needed."></textarea></div>
                <div class="form-field"><label class="form-label" for="duration">Duration</label><select class="form-control" id="duration" name="duration" required><option value="15">15 minutes</option><option value="30">30 minutes</option><option value="60">60 minutes</option></select></div>
            </div>
            <div class="platform-note" style="margin-top:16px">Support mode is read-only in SAAS-07. It provides an explicit target workspace and audit context; it does not sign in as an organization owner or expose passwords.</div>
            <div class="platform-form-actions"><button class="ui-button ui-button--primary" type="submit">Start support session</button></div>
        </form>
    </div></section>
    <section class="platform-card"><header class="platform-card__header"><div><h2>Current session</h2><p>Only your active support session is shown.</p></div></header><div class="platform-card__body">@if($current)<div class="platform-status-list"><div class="platform-status-row"><div class="platform-status-row__copy"><strong>{{ $current->organization?->name }}</strong><span>{{ $current->property?->name ?: 'Organization scope' }}</span></div><span class="ui-badge ui-badge--warning">Expires {{ $current->expires_at?->diffForHumans() }}</span></div></div><a class="ui-button ui-button--secondary" href="{{ route('platform.support.workspace', $current) }}" style="margin-top:14px">Open support workspace</a>@else<div class="platform-empty"><strong>No active support session.</strong><span>Starting support access creates an auditable record.</span></div>@endif</div></section>
</div>
<section class="platform-card" style="margin-top:18px"><header class="platform-card__header"><div><h2>Support session history</h2><p>Active, expired and ended sessions are retained.</p></div></header><div class="platform-table-wrap"><table class="platform-table"><thead><tr><th>Administrator</th><th>Organization</th><th>Property</th><th>Reason</th><th>Started</th><th>Expires</th><th>Status</th><th></th></tr></thead><tbody>@forelse($sessions as $session)<tr><td>{{ $session->administrator?->name }}</td><td>{{ $session->organization?->name }}</td><td>{{ $session->property?->name ?: '—' }}</td><td>{{ Str::limit($session->reason, 55) }}</td><td>{{ $session->started_at?->format('Y-m-d H:i') }}</td><td>{{ $session->expires_at?->format('Y-m-d H:i') }}</td><td><span class="ui-badge ui-badge--{{ $session->status === 'active' && $session->expires_at?->isFuture() ? 'warning' : 'neutral' }}">{{ ucfirst($session->status) }}</span></td><td>@if($session->isActive() && $session->platform_administrator_id === auth('platform')->id())<a class="ui-button ui-button--secondary ui-button--compact" href="{{ route('platform.support.workspace', $session) }}">Open</a>@endif</td></tr>@empty<tr><td colspan="8"><div class="platform-empty"><strong>No support sessions.</strong></div></td></tr>@endforelse</tbody></table></div><div class="platform-pagination">{{ $sessions->links() }}</div></section>
@endsection
