@php
    $variant = match (true) {
        request()->routeIs('dashboard') => 'dashboard',
        request()->routeIs('room-planning.*') => 'planning',
        request()->routeIs('profile') => 'profile',
        request()->routeIs('reports.*', 'finance.*') => 'reports',
        request()->routeIs('rooms.*') => 'rooms',
        request()->routeIs('settings.*') => 'settings',
        request()->routeIs('reservations.*', 'clients.*', 'housekeeping.*', 'maintenance.*', 'tasks.*', 'staff.*', 'payments.*', 'notifications.*') => 'list',
        request()->routeIs('*.show', '*.edit', '*.create') => 'detail',
        default => 'list',
    };
@endphp

<div class="app-page-skeleton" data-app-page-skeleton data-skeleton-variant="{{ $variant }}" hidden aria-hidden="true">
    <main class="app-page-skeleton__main">
        <div class="app-page-skeleton__template" data-skeleton-template="dashboard">
            <div class="app-page-skeleton__page-header"><div><x-ui.skeleton class="app-page-skeleton__title" /><x-ui.skeleton class="app-page-skeleton__subtitle" /></div><x-ui.skeleton class="app-page-skeleton__button" /></div>
            <div class="app-page-skeleton__metrics app-page-skeleton__metrics--six">@for($item = 0; $item < 6; $item++)<div class="app-page-skeleton__metric"><x-ui.skeleton class="app-page-skeleton__metric-icon" /><span><x-ui.skeleton class="app-page-skeleton__metric-label" /><x-ui.skeleton class="app-page-skeleton__metric-value" /><x-ui.skeleton class="app-page-skeleton__metric-meta" /></span></div>@endfor</div>
            <div class="app-page-skeleton__dashboard-grid"><div class="app-page-skeleton__card app-page-skeleton__card--chart"><div class="app-page-skeleton__card-header"><x-ui.skeleton class="app-page-skeleton__card-title" /><x-ui.skeleton class="app-page-skeleton__segmented" /></div><x-ui.skeleton class="app-page-skeleton__chart" /><div class="app-page-skeleton__legend"><x-ui.skeleton /><x-ui.skeleton /></div></div><div class="app-page-skeleton__card app-page-skeleton__card--status"><div class="app-page-skeleton__card-header"><x-ui.skeleton class="app-page-skeleton__card-title" /></div><div class="app-page-skeleton__status-content"><x-ui.skeleton class="app-page-skeleton__donut" /><div>@for($item = 0; $item < 5; $item++)<x-ui.skeleton class="app-page-skeleton__status-line" />@endfor</div></div></div></div>
            <div class="app-page-skeleton__dashboard-grid app-page-skeleton__dashboard-grid--secondary"><div class="app-page-skeleton__card app-page-skeleton__card--table"><div class="app-page-skeleton__card-header"><x-ui.skeleton class="app-page-skeleton__card-title" /><x-ui.skeleton class="app-page-skeleton__link" /></div><div class="app-page-skeleton__table-rows">@for($row = 0; $row < 4; $row++)<div class="app-page-skeleton__table-row">@for($cell = 0; $cell < 5; $cell++)<x-ui.skeleton />@endfor</div>@endfor</div></div><div class="app-page-skeleton__card app-page-skeleton__card--tasks"><div class="app-page-skeleton__card-header"><x-ui.skeleton class="app-page-skeleton__card-title" /><x-ui.skeleton class="app-page-skeleton__link" /></div>@for($row = 0; $row < 4; $row++)<div class="app-page-skeleton__task-row"><x-ui.skeleton class="app-page-skeleton__task-icon" /><span><x-ui.skeleton class="app-page-skeleton__task-title" /><x-ui.skeleton class="app-page-skeleton__task-detail" /></span><x-ui.skeleton class="app-page-skeleton__badge" /></div>@endfor</div></div>
        </div>

        <div class="app-page-skeleton__template" data-skeleton-template="list">
            <div class="app-page-skeleton__page-header"><div><x-ui.skeleton class="app-page-skeleton__title" /><x-ui.skeleton class="app-page-skeleton__subtitle" /></div><x-ui.skeleton class="app-page-skeleton__button" /></div>
            <div class="app-page-skeleton__metrics app-page-skeleton__metrics--four">@for($item = 0; $item < 4; $item++)<div class="app-page-skeleton__metric"><x-ui.skeleton class="app-page-skeleton__metric-icon" /><span><x-ui.skeleton class="app-page-skeleton__metric-label" /><x-ui.skeleton class="app-page-skeleton__metric-value" /><x-ui.skeleton class="app-page-skeleton__metric-meta" /></span></div>@endfor</div>
            <div class="app-page-skeleton__filter-toolbar">@for($item = 0; $item < 5; $item++)<x-ui.skeleton class="app-page-skeleton__filter-control" />@endfor<x-ui.skeleton class="app-page-skeleton__filter-button" /><x-ui.skeleton class="app-page-skeleton__filter-button app-page-skeleton__filter-button--secondary" /></div>
            <div class="app-page-skeleton__card app-page-skeleton__table-card"><div class="app-page-skeleton__card-header"><x-ui.skeleton class="app-page-skeleton__card-title" /><x-ui.skeleton class="app-page-skeleton__link" /></div><div class="app-page-skeleton__table-rows">@for($row = 0; $row < 7; $row++)<div class="app-page-skeleton__table-row app-page-skeleton__table-row--wide">@for($cell = 0; $cell < 7; $cell++)<x-ui.skeleton />@endfor</div>@endfor</div><div class="app-page-skeleton__pagination"><x-ui.skeleton /><x-ui.skeleton /><x-ui.skeleton /><x-ui.skeleton /></div></div>
        </div>

        <div class="app-page-skeleton__template" data-skeleton-template="reports">
            <div class="app-page-skeleton__page-header"><div><x-ui.skeleton class="app-page-skeleton__title" /><x-ui.skeleton class="app-page-skeleton__subtitle" /></div><x-ui.skeleton class="app-page-skeleton__button" /></div>
            <div class="app-page-skeleton__report-filters"><x-ui.skeleton /><x-ui.skeleton /><x-ui.skeleton class="app-page-skeleton__filter-button" /></div>
            <div class="app-page-skeleton__report-metrics">@for($item = 0; $item < 5; $item++)<div><x-ui.skeleton class="app-page-skeleton__report-label" /><x-ui.skeleton class="app-page-skeleton__report-value" /></div>@endfor</div>
            <div class="app-page-skeleton__report-panels"><div class="app-page-skeleton__card"><div class="app-page-skeleton__card-header"><x-ui.skeleton class="app-page-skeleton__card-title" /></div>@for($row = 0; $row < 5; $row++)<div class="app-page-skeleton__bar-row"><x-ui.skeleton /><x-ui.skeleton /><x-ui.skeleton /></div>@endfor</div><div class="app-page-skeleton__card"><div class="app-page-skeleton__card-header"><x-ui.skeleton class="app-page-skeleton__card-title" /></div>@for($row = 0; $row < 5; $row++)<div class="app-page-skeleton__bar-row"><x-ui.skeleton /><x-ui.skeleton /><x-ui.skeleton /></div>@endfor</div></div>
            <div class="app-page-skeleton__card app-page-skeleton__table-card"><div class="app-page-skeleton__card-header"><x-ui.skeleton class="app-page-skeleton__card-title" /></div><div class="app-page-skeleton__table-rows">@for($row = 0; $row < 5; $row++)<div class="app-page-skeleton__table-row app-page-skeleton__table-row--wide">@for($cell = 0; $cell < 6; $cell++)<x-ui.skeleton />@endfor</div>@endfor</div></div>
        </div>

        <div class="app-page-skeleton__template" data-skeleton-template="planning">
            <div class="app-page-skeleton__page-header"><div><x-ui.skeleton class="app-page-skeleton__title" /><x-ui.skeleton class="app-page-skeleton__subtitle" /></div><x-ui.skeleton class="app-page-skeleton__button" /></div>
            <div class="app-page-skeleton__planning-filters">@for($item = 0; $item < 6; $item++)<x-ui.skeleton />@endfor</div><div class="app-page-skeleton__planning-toolbar"><x-ui.skeleton class="app-page-skeleton__planning-switcher" /><x-ui.skeleton class="app-page-skeleton__planning-range" />@for($item = 0; $item < 4; $item++)<x-ui.skeleton class="app-page-skeleton__planning-button" />@endfor</div>
            <div class="app-page-skeleton__card app-page-skeleton__planning-card"><div class="app-page-skeleton__planning-grid"><div class="app-page-skeleton__planning-corner"><x-ui.skeleton /></div>@for($day = 0; $day < 8; $day++)<x-ui.skeleton class="app-page-skeleton__planning-day" />@endfor @for($row = 0; $row < 7; $row++)<x-ui.skeleton class="app-page-skeleton__planning-room" /><div class="app-page-skeleton__planning-track">@for($day = 0; $day < 8; $day++)<i></i>@endfor<x-ui.skeleton class="app-page-skeleton__planning-bar" /></div>@endfor</div></div>
        </div>

        <div class="app-page-skeleton__template" data-skeleton-template="profile">
            <div class="app-page-skeleton__page-header"><div><x-ui.skeleton class="app-page-skeleton__title app-page-skeleton__title--profile" /><x-ui.skeleton class="app-page-skeleton__subtitle app-page-skeleton__subtitle--profile" /></div></div>
            <div class="app-page-skeleton__profile-layout"><aside class="app-page-skeleton__profile-nav">@for($item = 0; $item < 5; $item++)<div><x-ui.skeleton class="app-page-skeleton__profile-nav-icon" /><x-ui.skeleton /></div>@endfor</aside><div class="app-page-skeleton__profile-content"><div class="app-page-skeleton__card app-page-skeleton__profile-picture"><div class="app-page-skeleton__card-header"><x-ui.skeleton class="app-page-skeleton__card-title" /></div><div class="app-page-skeleton__profile-picture-body"><x-ui.skeleton class="app-page-skeleton__avatar" /><div><x-ui.skeleton class="app-page-skeleton__profile-name" /><x-ui.skeleton class="app-page-skeleton__profile-copy" /><div class="app-page-skeleton__profile-actions"><x-ui.skeleton /><x-ui.skeleton /></div></div></div></div><div class="app-page-skeleton__card app-page-skeleton__profile-form"><div class="app-page-skeleton__card-header"><x-ui.skeleton class="app-page-skeleton__card-title" /></div><div class="app-page-skeleton__detail-hero"><x-ui.skeleton class="app-page-skeleton__avatar app-page-skeleton__avatar--small" /><span><x-ui.skeleton class="app-page-skeleton__profile-name" /><x-ui.skeleton class="app-page-skeleton__profile-copy" /></span></div><div class="app-page-skeleton__form-grid">@for($field = 0; $field < 6; $field++)<div><x-ui.skeleton class="app-page-skeleton__field-label" /><x-ui.skeleton class="app-page-skeleton__field" /></div>@endfor</div><div class="app-page-skeleton__form-footer"><x-ui.skeleton class="app-page-skeleton__button" /></div></div></div></div>
        </div>

        <div class="app-page-skeleton__template" data-skeleton-template="rooms">
            <div class="app-page-skeleton__page-header"><div><x-ui.skeleton class="app-page-skeleton__title" /><x-ui.skeleton class="app-page-skeleton__subtitle" /></div><x-ui.skeleton class="app-page-skeleton__button" /></div><div class="app-page-skeleton__room-tabs"><x-ui.skeleton /><x-ui.skeleton /><x-ui.skeleton /></div><div class="app-page-skeleton__filter-toolbar">@for($item = 0; $item < 4; $item++)<x-ui.skeleton class="app-page-skeleton__filter-control" />@endfor<x-ui.skeleton class="app-page-skeleton__filter-button" /></div><div class="app-page-skeleton__card app-page-skeleton__table-card"><div class="app-page-skeleton__card-header"><x-ui.skeleton class="app-page-skeleton__card-title" /><x-ui.skeleton class="app-page-skeleton__link" /></div><div class="app-page-skeleton__table-rows">@for($row = 0; $row < 6; $row++)<div class="app-page-skeleton__table-row app-page-skeleton__table-row--wide">@for($cell = 0; $cell < 6; $cell++)<x-ui.skeleton />@endfor</div>@endfor</div></div>
        </div>

        <div class="app-page-skeleton__template" data-skeleton-template="settings">
            <div class="app-page-skeleton__page-header"><div><x-ui.skeleton class="app-page-skeleton__title" /><x-ui.skeleton class="app-page-skeleton__subtitle" /></div></div><div class="app-page-skeleton__settings-layout"><aside class="app-page-skeleton__settings-nav">@for($item = 0; $item < 6; $item++)<x-ui.skeleton />@endfor</aside><div class="app-page-skeleton__settings-content"><div class="app-page-skeleton__card"><div class="app-page-skeleton__card-header"><x-ui.skeleton class="app-page-skeleton__card-title" /></div><div class="app-page-skeleton__form-grid">@for($field = 0; $field < 6; $field++)<div><x-ui.skeleton class="app-page-skeleton__field-label" /><x-ui.skeleton class="app-page-skeleton__field" /></div>@endfor</div><div class="app-page-skeleton__form-footer"><x-ui.skeleton class="app-page-skeleton__button" /></div></div><div class="app-page-skeleton__card app-page-skeleton__settings-card"><div class="app-page-skeleton__card-header"><x-ui.skeleton class="app-page-skeleton__card-title" /></div><x-ui.skeleton class="app-page-skeleton__settings-lines" /></div></div></div>
        </div>

        <div class="app-page-skeleton__template" data-skeleton-template="detail">
            <div class="app-page-skeleton__page-header"><div><x-ui.skeleton class="app-page-skeleton__title" /><x-ui.skeleton class="app-page-skeleton__subtitle" /></div><div class="app-page-skeleton__detail-actions"><x-ui.skeleton class="app-page-skeleton__button" /><x-ui.skeleton class="app-page-skeleton__button" /></div></div><div class="app-page-skeleton__detail-layout"><div class="app-page-skeleton__detail-main"><div class="app-page-skeleton__card"><div class="app-page-skeleton__detail-hero"><x-ui.skeleton class="app-page-skeleton__avatar app-page-skeleton__avatar--large" /><span><x-ui.skeleton class="app-page-skeleton__profile-name" /><x-ui.skeleton class="app-page-skeleton__profile-copy" /></span></div><div class="app-page-skeleton__form-grid">@for($field = 0; $field < 8; $field++)<div><x-ui.skeleton class="app-page-skeleton__field-label" /><x-ui.skeleton class="app-page-skeleton__field" /></div>@endfor</div></div><div class="app-page-skeleton__card app-page-skeleton__table-card"><div class="app-page-skeleton__card-header"><x-ui.skeleton class="app-page-skeleton__card-title" /></div><div class="app-page-skeleton__table-rows">@for($row = 0; $row < 4; $row++)<div class="app-page-skeleton__table-row">@for($cell = 0; $cell < 5; $cell++)<x-ui.skeleton />@endfor</div>@endfor</div></div></div><div class="app-page-skeleton__detail-side"><div class="app-page-skeleton__card"><div class="app-page-skeleton__card-header"><x-ui.skeleton class="app-page-skeleton__card-title" /></div><x-ui.skeleton class="app-page-skeleton__detail-block" /></div><div class="app-page-skeleton__card"><div class="app-page-skeleton__card-header"><x-ui.skeleton class="app-page-skeleton__card-title" /></div><x-ui.skeleton class="app-page-skeleton__detail-block" /></div></div></div>
        </div>
    </main>
</div>
