@extends('layouts.app')

@section('content')
<x-page-header title="POS Categories & Outlets" subtitle="Configure the places and product groups used by the terminal."><a class="ui-button ui-button--secondary" href="{{ route('pos.products') }}">Products</a></x-page-header>
<x-ui.tabs :tabs="[['label' => 'Categories', 'href' => route('pos.catalog', ['tab' => 'categories']), 'active' => $tab === 'categories'], ['label' => 'Outlets', 'href' => route('pos.catalog', ['tab' => 'outlets']), 'active' => $tab === 'outlets']]" />
@if($tab === 'categories')
<x-ui.card title="Categories" icon="grid"><x-slot:header>@can('pos.categories.manage')<a class="ui-button ui-button--primary" href="{{ route('pos.catalog', ['tab' => 'categories', 'new' => 1]) }}"><x-ui.icon name="plus" size="16" /> New category</a>@endcan</x-slot:header><x-data.table caption="POS categories"><thead><tr><th>Name</th><th>Code</th><th>Products</th><th>Sort</th><th>Actions</th></tr></thead><tbody>@forelse($categories as $category)<tr><td><strong>{{ $category->name }}</strong></td><td>{{ $category->code }}</td><td>{{ $category->products_count }}</td><td>{{ $category->sort_order }}</td><td><div class="row-actions">@can('pos.categories.manage')<a class="icon-button" href="{{ route('pos.catalog', ['tab' => 'categories', 'edit_category' => $category->id]) }}" aria-label="Edit category"><x-ui.icon name="edit" size="17" /></a><form method="POST" action="{{ route('pos.categories.destroy', $category) }}" data-confirm="Delete this POS category?">@csrf @method('DELETE')<button class="icon-button icon-button--danger" type="submit" aria-label="Delete category"><x-ui.icon name="trash" size="17" /></button></form>@endcan</div></td></tr>@empty<tr><td colspan="5">No POS categories configured.</td></tr>@endforelse</tbody></x-data.table></x-ui.card>
@if($openNew || $editCategory)<x-ui.modal id="pos-category-form" title="{{ $editCategory ? 'Edit POS category' : 'New POS category' }}" open="true"><form method="POST" action="{{ $editCategory ? route('pos.categories.update', $editCategory) : route('pos.categories.store') }}" class="pos-compact-form">@csrf @if($editCategory) @method('PUT') @endif<div class="settings-form-grid"><x-form.input name="name" label="Name" :value="old('name', $editCategory?->name)" required /><x-form.input name="code" label="Code" :value="old('code', $editCategory?->code)" required /><x-form.textarea name="description" label="Description" rows="2" field-class="form-field--full">{{ old('description', $editCategory?->description) }}</x-form.textarea><x-form.input name="sort_order" label="Display order" type="number" min="0" :value="old('sort_order', $editCategory?->sort_order ?? 0)" /><x-form.toggle name="is_active" label="Active" help="Available in POS" :checked="$editCategory?->is_active ?? true" /></div><div class="modal-form-footer"><button class="ui-button ui-button--primary" type="submit"><x-ui.icon name="save" size="16" /> Save category</button></div></form></x-ui.modal>@endif
@else
<x-ui.card title="Outlets" icon="building"><x-slot:header>@can('pos.outlets.manage')<a class="ui-button ui-button--primary" href="{{ route('pos.catalog', ['tab' => 'outlets', 'new' => 1]) }}"><x-ui.icon name="plus" size="16" /> New outlet</a>@endcan</x-slot:header><x-data.table caption="POS outlets"><thead><tr><th>Name</th><th>Code</th><th>Location</th><th>Products</th><th>Sales</th><th>Status</th><th>Actions</th></tr></thead><tbody>@forelse($outlets as $outlet)<tr><td><strong>{{ $outlet->name }}</strong></td><td>{{ $outlet->code }}</td><td>{{ $outlet->location ?: '—' }}</td><td>{{ $outlet->products_count }}</td><td>{{ $outlet->orders_count }}</td><td><x-ui.badge :variant="$outlet->is_active ? 'success' : 'neutral'">{{ $outlet->is_active ? 'Active' : 'Inactive' }}</x-ui.badge></td><td><div class="row-actions">@can('pos.outlets.manage')<a class="icon-button" href="{{ route('pos.catalog', ['tab' => 'outlets', 'edit_outlet' => $outlet->id]) }}" aria-label="Edit outlet"><x-ui.icon name="edit" size="17" /></a>@if(!$outlet->orders_count)<form method="POST" action="{{ route('pos.outlets.destroy', $outlet) }}" data-confirm="Delete this POS outlet?"><button class="icon-button icon-button--danger" type="submit" aria-label="Delete outlet"><x-ui.icon name="trash" size="17" /></button>@csrf @method('DELETE')</form>@endif @endcan</div></td></tr>@empty<tr><td colspan="7">No POS outlets configured.</td></tr>@endforelse</tbody></x-data.table></x-ui.card>
@if($openNew || $editOutlet)<x-ui.modal id="pos-outlet-form" title="{{ $editOutlet ? 'Edit POS outlet' : 'New POS outlet' }}" open="true"><form method="POST" action="{{ $editOutlet ? route('pos.outlets.update', $editOutlet) : route('pos.outlets.store') }}" class="pos-compact-form">@csrf @if($editOutlet) @method('PUT') @endif<div class="settings-form-grid"><x-form.input name="name" label="Name" :value="old('name', $editOutlet?->name)" required /><x-form.input name="code" label="Code" :value="old('code', $editOutlet?->code)" required /><x-form.input name="location" label="Location" :value="old('location', $editOutlet?->location)" /><x-form.textarea name="receipt_header" label="Receipt header" rows="3" field-class="form-field--full">{{ old('receipt_header', $editOutlet?->receipt_header) }}</x-form.textarea><x-form.toggle name="is_active" label="Active" help="Available for sales" :checked="$editOutlet?->is_active ?? true" /></div><div class="modal-form-footer"><button class="ui-button ui-button--primary" type="submit"><x-ui.icon name="save" size="16" /> Save outlet</button></div></form></x-ui.modal>@endif
@endif
@endsection
