@extends('layouts.app')

@section('content')
<x-page-header title="POS Sales" subtitle="Review orders, room charges and cashier activity."><a class="ui-button ui-button--primary" href="{{ route('pos.terminal') }}"><x-ui.icon name="plus" size="16" /> New sale</a></x-page-header>
<x-kpi-grid :items="$kpis" />
<form class="filter-toolbar" method="GET" action="{{ route('pos.orders') }}"><x-form.input name="search" value="{{ request('search') }}" placeholder="Order, guest or room" aria-label="Search sales" /><x-form.select name="status" aria-label="Filter status"><option value="all">All statuses</option>@foreach(['completed','voided','refunded'] as $status)<option value="{{ $status }}" @selected(request('status','all') === $status)>{{ ucfirst($status) }}</option>@endforeach</x-form.select><x-form.select name="scope" aria-label="Filter sales scope"><option value="all">All sales</option><option value="room_charges" @selected(request('scope') === 'room_charges')>Room charges</option></x-form.select><x-form.select name="outlet_id" aria-label="Filter outlet"><option value="">All outlets</option>@foreach($outlets as $outlet)<option value="{{ $outlet->id }}" @selected((string) request('outlet_id') === (string) $outlet->id)>{{ $outlet->name }}</option>@endforeach</x-form.select><x-form.input name="from" type="date" value="{{ request('from') }}" aria-label="From date" /><x-form.input name="to" type="date" value="{{ request('to') }}" aria-label="To date" /><button class="ui-button ui-button--info" type="submit"><x-ui.icon name="filter" size="16" /> Filter</button><a class="ui-button ui-button--secondary" href="{{ route('pos.orders') }}">Reset</a></form>
<section class="ui-card"><x-data.table caption="POS sales"><thead><tr><th>Order #</th><th>Date</th><th>Outlet</th><th>Guest / Room</th><th>Cashier</th><th>Items</th><th>Total</th><th>Payment</th><th>Status</th><th>Actions</th></tr></thead><tbody>@forelse($orders as $order)<tr><td><a class="text-link" href="{{ route('pos.orders.show', $order) }}">{{ $order->order_number }}</a></td><td>{{ $order->completed_at?->format('m/d/Y, h:i A') }}</td><td>{{ $order->outlet?->name }}</td><td>{{ $order->client?->full_name ?? 'Walk-in' }} @if($order->room)<small class="table-muted">Room {{ $order->room->room_number }}</small>@endif</td><td>{{ $order->cashier?->name }}</td><td>{{ $order->items->sum('quantity') }}</td><td><strong>{{ $formatter->format($order->total) }}</strong></td><td>{{ $order->payments->pluck('method')->map(fn($method) => ucwords(str_replace('_',' ', $method)))->join(', ') }}</td><td><x-ui.badge :variant="$order->status === 'completed' ? 'success' : ($order->status === 'refunded' ? 'neutral' : 'danger')">{{ ucfirst($order->status) }}</x-ui.badge></td><td><div class="row-actions"><a class="icon-button" href="{{ route('pos.receipts.show', $order) }}" aria-label="Receipt" data-tooltip="Receipt"><x-ui.icon name="document" size="17" /></a>@if($order->status === 'completed' && auth()->user()->hasPermission('pos.void'))<button class="icon-button icon-button--danger" type="button" data-modal-open="void-pos-{{ $order->id }}" aria-label="Void sale" data-tooltip="Void"><x-ui.icon name="trash" size="17" /></button>@endif</div></td></tr>@empty<tr><td colspan="10"><div class="empty-state"><strong>No POS sales found.</strong><span>Completed sales will appear here.</span></div></td></tr>@endforelse</tbody></x-data.table><x-data.pagination :paginator="$orders" /></section>
@foreach($orders as $order) @if($order->status === 'completed' && auth()->user()->hasPermission('pos.void'))<x-ui.modal id="void-pos-{{ $order->id }}" title="Void {{ $order->order_number }}"><p>This keeps the original transaction and restores tracked stock. Provide a reason.</p><form method="POST" action="{{ route('pos.orders.void', $order) }}">@csrf<x-form.textarea name="reason" label="Reason" rows="3" required /><div class="modal-form-footer"><button type="button" class="ui-button ui-button--secondary" data-modal-close>Cancel</button><button class="ui-button ui-button--danger" type="submit">Void sale</button></div></form></x-ui.modal>@endif @endforeach
@endsection
