const posTerminal = document.querySelector('[data-pos-terminal]');

if (posTerminal) {
    const cart = new Map();
    const products = posTerminal.querySelector('[data-pos-products]');
    const cartElement = posTerminal.querySelector('[data-pos-cart]');
    const feedback = document.querySelector('[data-pos-feedback]');
    const money = (value) => `${posTerminal.dataset.currencySymbol || ''}${new Intl.NumberFormat(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(Number(value || 0))}`;
    const quantityLabel = (value) => Number.isInteger(Number(value)) ? String(Number(value)) : Number(value).toFixed(3).replace(/0+$/, '').replace(/\.$/, '');
    const escapeHtml = (value) => String(value ?? '').replace(/[&<>'"]/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[character]));
    const showFeedback = (message, danger = false) => { if (!feedback) return; feedback.hidden = false; feedback.textContent = message; feedback.className = `pos-feedback ${danger ? 'pos-feedback--danger' : ''}`; };
    const selectedPayment = () => posTerminal.querySelector('[data-pos-payment]:checked')?.value || 'cash';
    const discountValue = () => Number(posTerminal.querySelector('[data-pos-discount]')?.value || 0);
    const discountType = () => posTerminal.querySelector('[name="discount_type"]')?.value || 'fixed';
    const totals = () => {
        let subtotal = 0; let tax = 0;
        cart.forEach((item) => { const base = item.price * item.quantity; const lineTax = item.taxInclusive ? base - (base / (1 + (item.taxRate / 100))) : base * (item.taxRate / 100); subtotal += base; tax += lineTax; });
        const rawDiscount = discountValue();
        const discount = Math.min(subtotal, discountType() === 'percentage' ? subtotal * Math.min(100, rawDiscount) / 100 : rawDiscount);
        return { subtotal, tax, discount, total: Math.max(0, subtotal - discount + tax) };
    };
    const renderCart = () => {
        const items = [...cart.values()];
        const summary = totals();
        posTerminal.querySelector('[data-pos-order-count]').textContent = `${items.reduce((sum, item) => sum + item.quantity, 0)} item${items.length === 1 ? '' : 's'}`;
        posTerminal.querySelector('[data-pos-subtotal]').textContent = money(summary.subtotal);
        posTerminal.querySelector('[data-pos-tax]').textContent = money(summary.tax);
        posTerminal.querySelector('[data-pos-total]').textContent = money(summary.total);
        posTerminal.querySelector('[data-pos-discount-total]')?.replaceChildren(document.createTextNode(money(summary.discount)));
        if (!items.length) { cartElement.innerHTML = '<div class="pos-cart__empty"><strong>Your order is empty</strong><span>Select products to begin a sale.</span></div>'; return; }
        cartElement.innerHTML = items.map((item) => `<div class="pos-cart-item"><div><strong>${escapeHtml(item.name)}</strong><small>${money(item.price)} each</small></div><div class="pos-cart-item__controls"><button type="button" data-pos-quantity="-" data-id="${item.id}" aria-label="Decrease ${escapeHtml(item.name)}">−</button><strong>${quantityLabel(item.quantity)}</strong><button type="button" data-pos-quantity="+" data-id="${item.id}" aria-label="Increase ${escapeHtml(item.name)}">+</button><button type="button" class="text-button text-button--danger" data-pos-remove="${item.id}" aria-label="Remove ${escapeHtml(item.name)}">×</button></div></div>`).join('');
    };
    const addProduct = (button) => {
        const id = String(button.dataset.id); const item = cart.get(id) || { id: Number(id), name: button.dataset.name, price: Number(button.dataset.price), quantity: 0, taxRate: Number(button.dataset.taxRate || 0), taxInclusive: button.dataset.taxInclusive === '1', trackStock: button.dataset.trackStock === '1', stock: Number(button.dataset.stock || 0) };
        if (item.trackStock && item.quantity >= item.stock) return showFeedback(`Insufficient stock for ${item.name}.`, true);
        item.quantity += 1; cart.set(id, item); renderCart();
    };
    products?.addEventListener('click', (event) => { const product = event.target.closest('[data-pos-product]'); if (product) addProduct(product); });
    cartElement?.addEventListener('click', (event) => { const plusMinus = event.target.closest('[data-pos-quantity]'); const remove = event.target.closest('[data-pos-remove]'); if (plusMinus) { const item = cart.get(String(plusMinus.dataset.id)); if (!item) return; if (plusMinus.dataset.posQuantity === '+' && (!item.trackStock || item.quantity < item.stock)) item.quantity += 1; else if (plusMinus.dataset.posQuantity === '-') item.quantity -= 1; if (item.quantity <= 0) cart.delete(String(item.id)); renderCart(); } if (remove) { cart.delete(String(remove.dataset.posRemove)); renderCart(); } });
    posTerminal.querySelector('[data-pos-clear]')?.addEventListener('click', () => { cart.clear(); renderCart(); });
    posTerminal.querySelector('[data-pos-discount]')?.addEventListener('input', renderCart); posTerminal.querySelector('[name="discount_type"]')?.addEventListener('change', renderCart);

    const renderProducts = (items) => { products.innerHTML = items.length ? items.map((product) => `<button type="button" class="pos-product-card" data-pos-product data-id="${product.id}" data-name="${escapeHtml(product.name)}" data-price="${product.price}" data-tax-rate="${product.tax_rate || 0}" data-tax-inclusive="${product.tax_inclusive ? 1 : 0}" data-track-stock="${product.track_stock ? 1 : 0}" data-stock="${product.stock_quantity || ''}"><span class="pos-product-card__icon" aria-hidden="true">▣</span><span class="pos-product-card__name">${escapeHtml(product.name)}</span><small>${escapeHtml(product.category || 'General')} ${product.sku ? `· ${escapeHtml(product.sku)}` : ''}</small><strong>${money(product.price)}</strong>${product.track_stock ? `<span class="pos-product-card__stock">${quantityLabel(product.stock_quantity)} in stock</span>` : ''}</button>`).join('') : '<div class="empty-state"><strong>No matching products.</strong><span>Try another search or category.</span></div>'; };
    let searchTimer; const searchInput = posTerminal.querySelector('[name="search"]'); searchInput?.addEventListener('input', () => { clearTimeout(searchTimer); searchTimer = setTimeout(async () => { const params = new URLSearchParams({ q: searchInput.value, outlet_id: posTerminal.querySelector('[data-pos-outlet]')?.value || '' }); try { renderProducts(await (await fetch(`${posTerminal.dataset.productSearchUrl}?${params}`)).json()); } catch { showFeedback('Product search is temporarily unavailable.', true); } }, 260); });
    posTerminal.querySelector('[data-pos-categories]')?.addEventListener('click', (event) => { const button = event.target.closest('[data-category]'); if (!button) return; posTerminal.querySelectorAll('[data-category]').forEach((item) => item.classList.toggle('is-active', item === button)); const category = button.dataset.category; products.querySelectorAll('[data-pos-product]').forEach((product) => { product.hidden = category !== 'all' && product.dataset.categoryId !== category; }); });

    const guestInput = posTerminal.querySelector('[data-pos-guest-search]'); const guestResults = posTerminal.querySelector('[data-pos-guest-results]'); const selectedGuest = posTerminal.querySelector('[data-pos-selected-guest]'); let guestTimer;
    const clearGuest = () => { posTerminal.querySelector('[data-pos-reservation]').value = ''; posTerminal.querySelector('[data-pos-client]').value = ''; posTerminal.querySelector('[data-pos-room]').value = ''; selectedGuest.hidden = true; guestInput.hidden = false; guestInput.value = ''; guestResults.hidden = true; };
    posTerminal.querySelector('[data-pos-clear-guest]')?.addEventListener('click', clearGuest);
    guestInput?.addEventListener('input', () => { clearTimeout(guestTimer); if (guestInput.value.trim().length < 2) { guestResults.hidden = true; return; } guestTimer = setTimeout(async () => { try { const params = new URLSearchParams({ q: guestInput.value }); const results = await (await fetch(`${posTerminal.dataset.guestSearchUrl}?${params}`)).json(); guestResults.innerHTML = results.length ? results.map((guest) => `<button type="button" data-pos-guest="${guest.id}" data-client="${guest.client_id}" data-room="${guest.room_id}" data-name="${escapeHtml(guest.client)}" data-detail="Room ${escapeHtml(guest.room)} · ${escapeHtml(guest.code)}">${escapeHtml(guest.client)}<small>Room ${escapeHtml(guest.room)} · ${escapeHtml(guest.code)}</small></button>`).join('') : '<span class="pos-guest-results__empty">No checked-in guest found.</span>'; guestResults.hidden = false; } catch { showFeedback('Guest search is temporarily unavailable.', true); } }, 260); });
    guestResults?.addEventListener('click', (event) => { const guest = event.target.closest('[data-pos-guest]'); if (!guest) return; posTerminal.querySelector('[data-pos-reservation]').value = guest.dataset.posGuest; posTerminal.querySelector('[data-pos-client]').value = guest.dataset.client; posTerminal.querySelector('[data-pos-room]').value = guest.dataset.room; selectedGuest.querySelector('[data-pos-selected-guest-name]').textContent = guest.dataset.name; selectedGuest.querySelector('[data-pos-selected-guest-detail]').textContent = guest.dataset.detail; selectedGuest.hidden = false; guestInput.hidden = true; guestResults.hidden = true; });
    posTerminal.querySelectorAll('[data-pos-payment]').forEach((input) => input.addEventListener('change', () => { posTerminal.querySelector('[data-pos-payment-reference]').hidden = input.value === 'cash' || input.value === 'charge_to_room'; }));
    const initialPayment = posTerminal.querySelector('[data-pos-payment]:checked');
    if (initialPayment) posTerminal.querySelector('[data-pos-payment-reference]').hidden = initialPayment.value === 'cash' || initialPayment.value === 'charge_to_room';
    posTerminal.addEventListener('submit', async (event) => { event.preventDefault(); if (!cart.size) return showFeedback('Add at least one product before completing the sale.', true); const summary = totals(); const key = `${Date.now()}-${Math.random().toString(36).slice(2)}`; posTerminal.querySelector('[data-pos-idempotency]').value = key; const formData = new FormData(posTerminal); const payload = { outlet_id: formData.get('outlet_id'), shift_id: formData.get('shift_id') || null, reservation_id: formData.get('reservation_id') || null, client_id: formData.get('client_id') || null, room_id: formData.get('room_id') || null, discount_type: formData.get('discount_type') || 'fixed', discount_value: formData.get('discount_value') || 0, idempotency_key: key, items: [...cart.values()].map((item) => ({ product_id: item.id, quantity: item.quantity })), payments: [{ method: selectedPayment(), amount: summary.total, reference: formData.get('payment_reference') || null }] }; const button = posTerminal.querySelector('[data-pos-complete]'); button.disabled = true; button.classList.add('is-loading'); try { const response = await fetch(posTerminal.action, { method: 'POST', headers: { 'Accept': 'application/json', 'Content-Type': 'application/json', 'X-CSRF-TOKEN': document.querySelector('meta[name="csrf-token"]').content }, body: JSON.stringify(payload) }); const result = await response.json(); if (!response.ok) throw new Error(result.message || 'Unable to complete sale.'); window.location.href = result.order.receipt_url; } catch (error) { showFeedback(error.message, true); button.disabled = false; button.classList.remove('is-loading'); } });
    renderCart();
}
