<?php

use App\Http\Controllers\Auth\ForgotPasswordController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\TwoFactorController;
use App\Http\Controllers\Clients\ClientController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\FinanceController;
use App\Http\Controllers\HousekeepingController;
use App\Http\Controllers\MaintenanceController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\OperationalDataTransferController;
use App\Http\Controllers\Payments\InvoiceController;
use App\Http\Controllers\Payments\PaymentController;
use App\Http\Controllers\PosController;
use App\Http\Controllers\PublicMetadataController;
use App\Http\Controllers\PublicContactController;
use App\Http\Controllers\ContactEnquiryController;
use App\Http\Controllers\WebsiteController;
use App\Http\Controllers\ReportsController;
use App\Http\Controllers\Reservations\ReservationController;
use App\Http\Controllers\RoomPlanningController;
use App\Http\Controllers\Rooms\RoomController;
use App\Http\Controllers\SearchController;
use App\Http\Controllers\SettingsController;
use App\Http\Controllers\SetupController;
use App\Http\Controllers\TaskController;
use App\Http\Controllers\TenantContextController;
use App\Http\Controllers\PropertyManagementController;
use App\Http\Controllers\OrganizationSettingsController;
use App\Http\Controllers\OrganizationMemberController;
use App\Http\Controllers\OrganizationAuditController;
use App\Http\Controllers\Staff\ProfileController;
use App\Http\Controllers\Staff\StaffController;
use App\Http\Controllers\WebhookController;
use App\Http\Controllers\Announcements\AnnouncementController;
use App\Http\Controllers\Platform\PlatformAuthController;
use App\Http\Controllers\Platform\PlatformController;
use App\Http\Controllers\Platform\PlatformTwoFactorController;
use App\Http\Controllers\Platform\PlatformSupportWorkspaceController;
use App\Http\Controllers\Webhooks\PaymentGatewayWebhookController;
use App\Http\Middleware\ConfiguredSessionSecurity;
use App\Http\Middleware\EnsureActiveUser;
use App\Http\Middleware\EnsureInstallationComplete;
use App\Http\Middleware\EnsureInstallationIncomplete;
use App\Http\Middleware\EnsurePasswordChanged;
use Illuminate\Support\Facades\Route;

Route::view('/', 'public.home')->name('public.home');
Route::view('/product', 'public.product')->name('public.product');
Route::view('/operations', 'public.operations')->name('public.operations');
Route::view('/pos', 'public.pos')->name('public.pos');
Route::view('/finance', 'public.finance')->name('public.finance');
Route::view('/security', 'public.security')->name('public.security');
Route::view('/integrations', 'public.integrations')->name('public.integrations');
Route::view('/pricing', 'public.pricing')->name('public.pricing');
Route::get('/contact', [PublicContactController::class, 'create'])->name('public.contact');
Route::post('/contact', [PublicContactController::class, 'store'])->middleware('throttle:5,60')->name('public.contact.submit');
Route::get('/sitemap.xml', [PublicMetadataController::class, 'sitemap'])->name('sitemap');
Route::get('/robots.txt', [PublicMetadataController::class, 'robots'])->name('robots');

Route::middleware(EnsureInstallationIncomplete::class)->prefix('setup')->name('setup.')->group(function () {
    Route::get('/', [SetupController::class, 'index'])->name('index');
    Route::post('/operating-mode', [SetupController::class, 'operatingMode'])->name('operating-mode');
    Route::post('/complete', [SetupController::class, 'complete'])->name('complete');
});
Route::get('/setup/finish', [SetupController::class, 'finish'])->name('setup.finish');
Route::post('/webhooks/payments/{provider}', PaymentGatewayWebhookController::class)->name('webhooks.payments');
Route::post('/webhooks/{provider}/{type}', [WebhookController::class, 'inbound'])->whereIn('type', ['whatsapp', 'channels'])->name('webhooks.inbound');

Route::prefix('platform')->name('platform.')->group(function (): void {
    Route::middleware('guest:platform')->group(function (): void {
        Route::get('/login', [PlatformAuthController::class, 'create'])->name('login');
        Route::post('/login', [PlatformAuthController::class, 'store'])->middleware('throttle:platform-login')->name('login.store');
    });

    Route::middleware('platform.2fa.pending')->group(function (): void {
        Route::get('/two-factor/enroll', [PlatformTwoFactorController::class, 'enroll'])->name('2fa.enroll');
        Route::post('/two-factor/enroll', [PlatformTwoFactorController::class, 'confirmEnrollment'])->name('2fa.enroll.confirm');
        Route::get('/two-factor/challenge', [PlatformTwoFactorController::class, 'challenge'])->name('2fa.challenge');
        Route::post('/two-factor/challenge', [PlatformTwoFactorController::class, 'verifyChallenge'])->name('2fa.challenge.verify');
    });

    Route::middleware(['platform.auth', 'platform.active', 'platform.2fa'])->group(function (): void {
        Route::post('/logout', [PlatformAuthController::class, 'destroy'])->name('logout');
        Route::get('/', [PlatformController::class, 'dashboard'])->middleware('platform.permission:platform.dashboard.view')->name('dashboard');
        Route::get('/organizations', [PlatformController::class, 'organizations'])->middleware('platform.permission:platform.organizations.view')->name('organizations');
        Route::get('/organizations/{organization}', [PlatformController::class, 'organization'])->middleware('platform.permission:platform.organizations.view')->name('organizations.show');
        Route::get('/properties', [PlatformController::class, 'properties'])->middleware('platform.permission:platform.properties.view')->name('properties');
        Route::get('/properties/{property}', [PlatformController::class, 'property'])->middleware('platform.permission:platform.properties.view')->name('properties.show');
        Route::get('/subscriptions', [PlatformController::class, 'subscriptions'])->middleware('platform.permission:platform.subscriptions.view')->name('subscriptions');
        Route::get('/subscriptions/{subscription}', [PlatformController::class, 'subscription'])->middleware('platform.permission:platform.subscriptions.view')->name('subscriptions.show');
        Route::patch('/organizations/{organization}/subscription/plan', [PlatformController::class, 'assignPlan'])->middleware('platform.permission:platform.subscriptions.assign_plan')->name('organizations.subscription.plan');
        Route::get('/plans', [PlatformController::class, 'plans'])->middleware('platform.permission:platform.plans.view')->name('plans');
        Route::get('/plans/create', [PlatformController::class, 'createPlan'])->middleware('platform.permission:platform.plans.manage')->name('plans.create');
        Route::post('/plans', [PlatformController::class, 'storePlan'])->middleware('platform.permission:platform.plans.manage')->name('plans.store');
        Route::get('/plans/{plan}', [PlatformController::class, 'plan'])->middleware('platform.permission:platform.plans.view')->name('plans.show');
        Route::get('/plans/{plan}/edit', [PlatformController::class, 'editPlan'])->middleware('platform.permission:platform.plans.manage')->name('plans.edit');
        Route::patch('/plans/{plan}', [PlatformController::class, 'updatePlan'])->middleware('platform.permission:platform.plans.manage')->name('plans.update');
        Route::get('/features', [PlatformController::class, 'features'])->middleware('platform.permission:platform.features.view')->name('features');
        Route::get('/support', [PlatformController::class, 'support'])->middleware('platform.permission:platform.support.view')->name('support');
        Route::post('/support', [PlatformController::class, 'startSupport'])->middleware('platform.permission:platform.support.start')->name('support.start');
        Route::post('/support/end', [PlatformController::class, 'endSupport'])->middleware('platform.permission:platform.support.start')->name('support.end');
        Route::post('/support/{platformSupportSession}/enter', [PlatformController::class, 'enterSupport'])->middleware('platform.permission:platform.support.start')->name('support.enter');
        Route::prefix('/support/{platformSupportSession}/workspace')->middleware(['platform.permission:platform.support.start', 'platform.support.context', 'platform.support.readonly'])->group(function (): void {
            Route::get('/', [PlatformSupportWorkspaceController::class, 'dashboard'])->name('support.workspace');
            Route::get('/search', [PlatformSupportWorkspaceController::class, 'search'])->name('support.workspace.search');
            Route::get('/{module}', [PlatformSupportWorkspaceController::class, 'module'])->whereIn('module', ['reservations', 'clients', 'rooms', 'room-planning', 'tasks', 'housekeeping', 'maintenance', 'pos', 'finance', 'reports', 'settings'])->name('support.workspace.module');
            Route::get('/{module}/{id}', [PlatformSupportWorkspaceController::class, 'detail'])->whereIn('module', ['reservations', 'clients'])->whereNumber('id')->name('support.workspace.detail');
        });
        Route::get('/health', [PlatformController::class, 'health'])->middleware('platform.permission:platform.health.view')->name('health');
        Route::get('/audit-logs', [PlatformController::class, 'audit'])->middleware('platform.permission:platform.audit.view')->name('audit');
        Route::get('/administrators', [PlatformController::class, 'administrators'])->middleware('platform.permission:platform.administrators.manage')->name('administrators');
        Route::post('/administrators', [PlatformController::class, 'storeAdministrator'])->middleware('platform.permission:platform.administrators.manage')->name('administrators.store');
        Route::patch('/administrators/{platformAdministrator}/status', [PlatformController::class, 'updateAdministratorStatus'])->middleware('platform.permission:platform.administrators.manage')->name('administrators.status');
        Route::get('/profile', [PlatformController::class, 'profile'])->name('profile');
        Route::put('/profile/password', [PlatformController::class, 'updatePassword'])->name('profile.password');
        Route::get('/two-factor/recovery-codes', [PlatformTwoFactorController::class, 'recoveryCodes'])->name('2fa.recovery');
        Route::post('/profile/two-factor/recovery-codes', [PlatformTwoFactorController::class, 'regenerate'])->name('profile.2fa.recovery-codes');
        Route::post('/profile/two-factor/reset', [PlatformTwoFactorController::class, 'reset'])->name('profile.2fa.reset');
    });
});

Route::middleware(['guest', EnsureInstallationComplete::class])->group(function () {
    Route::get('/login', [LoginController::class, 'create'])->name('login');
    Route::post('/login', [LoginController::class, 'store'])->name('login.store');
    Route::get('/forgot-password', [ForgotPasswordController::class, 'request'])->name('password.request');
    Route::post('/forgot-password', [ForgotPasswordController::class, 'send'])->name('password.email');
    Route::get('/reset-password/{token}', [ForgotPasswordController::class, 'reset'])->name('password.reset');
    Route::post('/reset-password', [ForgotPasswordController::class, 'update'])->name('password.update');
});
Route::middleware([EnsureInstallationComplete::class, 'throttle:6,1'])->group(function () {
    Route::get('/two-factor-challenge', [TwoFactorController::class, 'create'])->name('two-factor.login');
    Route::post('/two-factor-challenge', [TwoFactorController::class, 'store'])->name('two-factor.login.store');
});

Route::middleware(['auth', EnsureActiveUser::class, EnsureInstallationComplete::class, ConfiguredSessionSecurity::class, EnsurePasswordChanged::class, 'tenant.context'])->group(function () {
    Route::post('/logout', [LoginController::class, 'destroy'])->name('logout');
    Route::post('/context/property', [TenantContextController::class, 'property'])->name('context.property');
    Route::post('/context/organization', [TenantContextController::class, 'organization'])->name('context.organization');
    Route::get('/management/contact-enquiries', [ContactEnquiryController::class, 'index'])->middleware('can:contact_enquiries.view')->name('contact-enquiries.index');
    Route::get('/management/contact-enquiries/{contactEnquiry}', [ContactEnquiryController::class, 'show'])->middleware('can:contact_enquiries.view')->name('contact-enquiries.show');
    Route::patch('/management/contact-enquiries/{contactEnquiry}/status', [ContactEnquiryController::class, 'updateStatus'])->middleware('can:contact_enquiries.manage')->name('contact-enquiries.status');
    Route::prefix('admin/website')->name('website.')->group(function () {
        Route::get('/', [WebsiteController::class, 'dashboard'])->middleware('can:website.view')->name('dashboard');
        Route::get('/pages', [WebsiteController::class, 'pages'])->middleware('can:website.pages.manage')->name('pages.index');
        Route::get('/pages/{websitePage}/edit', [WebsiteController::class, 'edit'])->middleware('can:website.pages.manage')->name('pages.edit');
        Route::patch('/pages/{websitePage}', [WebsiteController::class, 'update'])->middleware('can:website.pages.manage')->name('pages.update');
        Route::post('/pages/{websitePage}/publish', [WebsiteController::class, 'publish'])->middleware('can:website.pages.publish')->name('pages.publish');
        Route::get('/pages/{websitePage}/preview', [WebsiteController::class, 'preview'])->middleware('can:website.pages.manage')->name('pages.preview');
        Route::get('/pages/{websitePage}/revisions', [WebsiteController::class, 'revisions'])->middleware('can:website.pages.manage')->name('pages.revisions');
        Route::post('/pages/{websitePage}/revisions/{websiteRevision}/restore', [WebsiteController::class, 'restoreRevision'])->middleware('can:website.pages.manage')->name('pages.revisions.restore');
        Route::post('/pages/{websitePage}/sections/{websiteSection}/{direction}', [WebsiteController::class, 'moveSection'])->whereIn('direction', ['up', 'down'])->middleware('can:website.pages.manage')->name('pages.sections.move');
        Route::get('/media', [WebsiteController::class, 'media'])->middleware('can:website.media.manage')->name('media');
        Route::post('/media', [WebsiteController::class, 'uploadMedia'])->middleware('can:website.media.manage')->name('media.upload');
        Route::delete('/media/{websiteMedia}', [WebsiteController::class, 'archiveMedia'])->middleware('can:website.media.manage')->name('media.archive');
        Route::get('/navigation', [WebsiteController::class, 'navigation'])->middleware('can:website.navigation.manage')->name('navigation');
        Route::patch('/navigation', [WebsiteController::class, 'updateNavigation'])->middleware('can:website.navigation.manage')->name('navigation.update');
        Route::get('/pricing', [WebsiteController::class, 'pricing'])->middleware('can:website.pricing.manage')->name('pricing');
        Route::patch('/pricing/{websitePricingPlan}', [WebsiteController::class, 'updatePricing'])->middleware('can:website.pricing.manage')->name('pricing.update');
        Route::get('/seo', [WebsiteController::class, 'seo'])->middleware('can:website.seo.manage')->name('seo');
        Route::get('/settings', [WebsiteController::class, 'settings'])->middleware('can:website.settings.manage')->name('settings');
        Route::patch('/settings', [WebsiteController::class, 'updateSettings'])->middleware('can:website.settings.manage')->name('settings.update');
        Route::get('/enquiries', [ContactEnquiryController::class, 'index'])->middleware('can:website.enquiries.view')->name('enquiries');
        Route::get('/enquiries/{contactEnquiry}', [ContactEnquiryController::class, 'show'])->middleware('can:website.enquiries.view')->name('enquiries.show');
        Route::patch('/enquiries/{contactEnquiry}/status', [ContactEnquiryController::class, 'updateStatus'])->middleware('can:website.enquiries.manage')->name('enquiries.status');
    });
    Route::get('/dashboard', DashboardController::class)->name('dashboard');
    Route::get('/search', [SearchController::class, 'index'])->name('search');

    Route::get('/data-transfer/{resource}/export/{format}', [OperationalDataTransferController::class, 'export'])->whereIn('resource', ['rooms', 'clients', 'staff', 'tasks', 'maintenance', 'housekeeping'])->whereIn('format', ['csv', 'pdf'])->name('data-transfer.export');
    Route::get('/data-transfer/{resource}/template', [OperationalDataTransferController::class, 'template'])->whereIn('resource', ['rooms', 'clients', 'staff', 'tasks', 'maintenance', 'housekeeping'])->name('data-transfer.template');
    Route::post('/data-transfer/{resource}/import', [OperationalDataTransferController::class, 'import'])->whereIn('resource', ['rooms', 'clients', 'staff', 'tasks', 'maintenance', 'housekeeping'])->name('data-transfer.import');

    Route::get('/reservations/export', [ReservationController::class, 'export'])->name('reservations.export');
    Route::post('/reservations/{reservation}/check-in', [ReservationController::class, 'checkIn'])->name('reservations.check-in');
    Route::post('/reservations/{reservation}/check-out', [ReservationController::class, 'checkOut'])->name('reservations.check-out');
    Route::post('/reservations/{reservation}/cancel', [ReservationController::class, 'cancel'])->name('reservations.cancel');
    Route::post('/reservations/{reservation}/no-show', [ReservationController::class, 'noShow'])->name('reservations.no-show');
    Route::resource('reservations', ReservationController::class)->only(['index', 'create', 'store', 'show', 'edit', 'update', 'destroy']);
    Route::get('/room-planning/data', [RoomPlanningController::class, 'data'])->middleware('feature:room_planning')->name('room-planning.data');
    Route::get('/room-planning/available-rooms', [RoomPlanningController::class, 'availableRooms'])->middleware('feature:room_planning')->name('room-planning.available-rooms');
    Route::get('/room-planning', [RoomPlanningController::class, 'index'])->middleware('feature:room_planning')->name('room-planning.index');
    Route::resource('clients', ClientController::class)->only(['index', 'create', 'store', 'show', 'edit', 'update', 'destroy']);
    Route::resource('tasks', TaskController::class)->only(['index', 'create', 'store', 'show', 'edit', 'update']);
    Route::post('/tasks/{task}/complete', [TaskController::class, 'complete'])->name('tasks.complete');
    Route::patch('/tasks/{task}/status', [TaskController::class, 'status'])->name('tasks.status');
    Route::post('/tasks/{task}/reopen', [TaskController::class, 'reopen'])->name('tasks.reopen');
    Route::post('/tasks/{task}/archive', [TaskController::class, 'archive'])->name('tasks.archive');
    Route::put('/tasks/{task}/assign', [TaskController::class, 'assign'])->name('tasks.assign');
    Route::post('/tasks/{task}/comments', [TaskController::class, 'comment'])->name('tasks.comments.store');
    Route::post('/tasks/{task}/subtasks', [TaskController::class, 'subtask'])->name('tasks.subtasks.store');
    Route::patch('/tasks/{task}/subtasks/{subtask}', [TaskController::class, 'toggleSubtask'])->name('tasks.subtasks.toggle');
    Route::post('/tasks/{task}/attachments', [TaskController::class, 'upload'])->name('tasks.attachments.store');
    Route::get('/tasks/{task}/attachments/{attachment}', [TaskController::class, 'download'])->name('tasks.attachments.download');
    Route::delete('/tasks/{task}/attachments/{attachment}', [TaskController::class, 'deleteAttachment'])->name('tasks.attachments.destroy');
    Route::post('/tasks/{task}/timer/start', [TaskController::class, 'startTimer'])->name('tasks.timer.start');
    Route::post('/tasks/{task}/timer/stop', [TaskController::class, 'stopTimer'])->name('tasks.timer.stop');
    Route::post('/rooms/{room}/status', [RoomController::class, 'status'])->name('rooms.status');
    Route::post('/rooms/categories', [RoomController::class, 'categoryStore'])->name('rooms.categories.store');
    Route::put('/rooms/categories/{category}', [RoomController::class, 'categoryUpdate'])->name('rooms.categories.update');
    Route::delete('/rooms/categories/{category}', [RoomController::class, 'categoryDestroy'])->name('rooms.categories.destroy');
    Route::post('/rooms/types', [RoomController::class, 'typeStore'])->name('rooms.types.store');
    Route::put('/rooms/types/{type}', [RoomController::class, 'typeUpdate'])->name('rooms.types.update');
    Route::delete('/rooms/types/{type}', [RoomController::class, 'typeDestroy'])->name('rooms.types.destroy');
    Route::post('/rooms/floors', [RoomController::class, 'floorStore'])->name('rooms.floors.store');
    Route::put('/rooms/floors/{floor}', [RoomController::class, 'floorUpdate'])->name('rooms.floors.update');
    Route::delete('/rooms/floors/{floor}', [RoomController::class, 'floorDestroy'])->name('rooms.floors.destroy');
    Route::post('/rooms/statuses', [RoomController::class, 'statusStore'])->name('rooms.statuses.store');
    Route::put('/rooms/statuses/{status}', [RoomController::class, 'statusUpdate'])->name('rooms.statuses.update');
    Route::delete('/rooms/statuses/{status}', [RoomController::class, 'statusDestroy'])->name('rooms.statuses.destroy');
    Route::resource('rooms', RoomController::class)->only(['index', 'create', 'store', 'show', 'edit', 'update', 'destroy']);
    Route::post('/housekeeping/{housekeeping}/complete', [HousekeepingController::class, 'complete'])->name('housekeeping.complete');
    Route::resource('housekeeping', HousekeepingController::class)->only(['index', 'create', 'store', 'edit', 'update', 'destroy']);
    Route::post('/maintenance/{maintenance}/complete', [MaintenanceController::class, 'complete'])->name('maintenance.complete');
    Route::resource('maintenance', MaintenanceController::class)->only(['index', 'create', 'store', 'edit', 'update', 'destroy']);
    Route::post('/staff/{staff}/disable', [StaffController::class, 'destroy'])->name('staff.disable');
    Route::post('/staff/{staff}/reset-password', [StaffController::class, 'resetPassword'])->name('staff.reset-password');
    Route::post('/staff/departments', [StaffController::class, 'departmentStore'])->name('staff.departments.store');
    Route::put('/staff/departments/{department}', [StaffController::class, 'departmentUpdate'])->name('staff.departments.update');
    Route::delete('/staff/departments/{department}', [StaffController::class, 'departmentDestroy'])->name('staff.departments.destroy');
    Route::put('/staff/roles/{role}', [StaffController::class, 'roleUpdate'])->name('staff.roles.update');
    Route::get('/staff/profile', [ProfileController::class, 'profile'])->name('profile');
    Route::get('/staff/profile/avatar', [ProfileController::class, 'avatar'])->name('profile.avatar');
    Route::put('/staff/profile/avatar', [ProfileController::class, 'updateAvatar'])->name('profile.avatar.update');
    Route::put('/staff/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::put('/staff/profile/theme', [ProfileController::class, 'updateTheme'])->name('profile.theme.update');
    Route::post('/staff/profile/email/request', [ProfileController::class, 'requestEmailChange'])->name('profile.email.request');
    Route::post('/staff/profile/email/verify', [ProfileController::class, 'verifyEmailChange'])->name('profile.email.verify');
    Route::put('/staff/profile/preferences', [ProfileController::class, 'updatePreferences'])->name('profile.preferences.update');
    Route::post('/staff/profile/two-factor/enable', [ProfileController::class, 'enableTwoFactor'])->name('profile.two-factor.enable');
    Route::post('/staff/profile/two-factor/confirm', [ProfileController::class, 'confirmTwoFactor'])->name('profile.two-factor.confirm');
    Route::post('/staff/profile/two-factor/disable', [ProfileController::class, 'disableTwoFactor'])->name('profile.two-factor.disable');
    Route::post('/staff/profile/two-factor/recovery-codes', [ProfileController::class, 'regenerateRecoveryCodes'])->name('profile.two-factor.recovery-codes');
    Route::post('/staff/profile/login-history/forget-others', [ProfileController::class, 'forgetOtherLoginDevices'])->name('profile.login-history.forget-others');
    Route::post('/staff/profile/login-history/{history}/forget', [ProfileController::class, 'forgetLoginDevice'])->name('profile.login-history.forget');
    Route::get('/password/change', [ProfileController::class, 'password'])->name('password.change');
    Route::put('/password/change', [ProfileController::class, 'updatePassword'])->name('password.change.update');
    Route::resource('staff', StaffController::class)->only(['index', 'create', 'store', 'show', 'edit', 'update', 'destroy']);
    Route::get('/payments/export', [PaymentController::class, 'export'])->name('payments.export');
    Route::get('/payments/print', [PaymentController::class, 'print'])->name('payments.print');
    Route::post('/payments/{payment}/void', [PaymentController::class, 'void'])->name('payments.void');
    Route::post('/payments/{payment}/refund', [PaymentController::class, 'refund'])->name('payments.refund');
    Route::resource('payments', PaymentController::class)->only(['index', 'store', 'update', 'destroy']);
    Route::get('/finance/overview', [FinanceController::class, 'overview'])->middleware('feature:finance')->name('finance.overview');
    Route::get('/finance/transactions', [FinanceController::class, 'transactions'])->middleware('feature:finance')->name('finance.transactions');
    Route::get('/finance/expenses', [FinanceController::class, 'expenses'])->middleware('feature:finance')->name('finance.expenses');
    Route::post('/finance/expenses', [FinanceController::class, 'expenseStore'])->middleware('feature:finance')->name('finance.expenses.store');
    Route::post('/finance/expenses/{expense}/{action}', [FinanceController::class, 'expenseAction'])->whereIn('action', ['submit', 'approve', 'reject', 'pay', 'reverse'])->middleware('feature:finance')->name('finance.expenses.action');
    Route::get('/finance/expenses/{expense}/attachment', [FinanceController::class, 'attachment'])->middleware('feature:finance')->name('finance.expenses.attachment');
    Route::get('/finance/accounts', [FinanceController::class, 'accounts'])->middleware('feature:finance')->name('finance.accounts');
    Route::post('/finance/accounts', [FinanceController::class, 'accountStore'])->middleware('feature:finance')->name('finance.accounts.store');
    Route::get('/finance/transfers', [FinanceController::class, 'transfers'])->middleware('feature:finance')->name('finance.transfers');
    Route::post('/finance/transfers', [FinanceController::class, 'transferStore'])->middleware('feature:finance')->name('finance.transfers.store');
    Route::get('/finance/reports', [FinanceController::class, 'reports'])->middleware('feature:finance')->name('finance.reports');
    Route::get('/finance/exports/{report}', [FinanceController::class, 'export'])->middleware('feature:finance')->name('finance.exports');
    Route::get('/finance/petty-cash', [FinanceController::class, 'pettyCash'])->middleware('feature:finance')->name('finance.petty-cash');
    Route::post('/finance/petty-cash/close', [FinanceController::class, 'cashCloseStore'])->middleware('feature:finance')->name('finance.petty-cash.close');
    Route::get('/finance/reconciliation', [FinanceController::class, 'reconciliation'])->middleware('feature:finance')->name('finance.reconciliation');
    Route::post('/finance/reconciliation', [FinanceController::class, 'reconciliationStore'])->middleware('feature:finance')->name('finance.reconciliation.store');
    Route::get('/invoices/{invoice}', [InvoiceController::class, 'show'])->name('invoices.show');
    Route::get('/invoices/{invoice}/print', [InvoiceController::class, 'print'])->name('invoices.print');
    Route::get('/invoices/{invoice}/download', [InvoiceController::class, 'download'])->name('invoices.download');
    Route::get('/reports', [ReportsController::class, 'index'])->middleware('feature:reports')->name('reports.index');
    Route::get('/reports/export', [ReportsController::class, 'export'])->middleware('feature:reports')->name('reports.export');
    Route::get('/pos/terminal', [PosController::class, 'terminal'])->middleware('feature:pos')->name('pos.terminal');
    Route::get('/pos/products/search', [PosController::class, 'productSearch'])->middleware('feature:pos')->name('pos.products.search');
    Route::get('/pos/guests/search', [PosController::class, 'guestSearch'])->middleware('feature:pos')->name('pos.guests.search');
    Route::post('/pos/checkout', [PosController::class, 'checkout'])->middleware('feature:pos')->name('pos.checkout');
    Route::get('/pos/orders', [PosController::class, 'orders'])->middleware('feature:pos')->name('pos.orders');
    Route::get('/pos/orders/{order}', [PosController::class, 'showOrder'])->middleware('feature:pos')->name('pos.orders.show');
    Route::post('/pos/orders/{order}/void', [PosController::class, 'void'])->middleware('feature:pos')->name('pos.orders.void');
    Route::post('/pos/orders/{order}/refund', [PosController::class, 'refund'])->middleware('feature:pos')->name('pos.orders.refund');
    Route::get('/pos/receipts/{order}', [PosController::class, 'receipt'])->middleware('feature:pos')->name('pos.receipts.show');
    Route::get('/pos/receipts/{order}/download', [PosController::class, 'receiptDownload'])->middleware('feature:pos')->name('pos.receipts.download');
    Route::get('/pos/products', [PosController::class, 'products'])->middleware('feature:pos')->name('pos.products');
    Route::post('/pos/products', [PosController::class, 'productStore'])->middleware('feature:pos')->name('pos.products.store');
    Route::put('/pos/products/{product}', [PosController::class, 'productUpdate'])->middleware('feature:pos')->name('pos.products.update');
    Route::delete('/pos/products/{product}', [PosController::class, 'productDestroy'])->middleware('feature:pos')->name('pos.products.destroy');
    Route::get('/pos/catalog', [PosController::class, 'catalog'])->middleware('feature:pos')->name('pos.catalog');
    Route::post('/pos/categories', [PosController::class, 'categoryStore'])->middleware('feature:pos')->name('pos.categories.store');
    Route::put('/pos/categories/{category}', [PosController::class, 'categoryUpdate'])->middleware('feature:pos')->name('pos.categories.update');
    Route::delete('/pos/categories/{category}', [PosController::class, 'categoryDestroy'])->middleware('feature:pos')->name('pos.categories.destroy');
    Route::post('/pos/outlets', [PosController::class, 'outletStore'])->middleware('feature:pos')->name('pos.outlets.store');
    Route::put('/pos/outlets/{outlet}', [PosController::class, 'outletUpdate'])->middleware('feature:pos')->name('pos.outlets.update');
    Route::delete('/pos/outlets/{outlet}', [PosController::class, 'outletDestroy'])->middleware('feature:pos')->name('pos.outlets.destroy');
    Route::get('/pos/shifts', [PosController::class, 'shifts'])->middleware('feature:pos')->name('pos.shifts');
    Route::post('/pos/shifts', [PosController::class, 'shiftOpen'])->middleware('feature:pos')->name('pos.shifts.open');
    Route::post('/pos/shifts/{shift}/close', [PosController::class, 'shiftClose'])->middleware('feature:pos')->name('pos.shifts.close');
    Route::get('/pos/reports', [PosController::class, 'reports'])->middleware('feature:pos')->name('pos.reports');
    Route::get('/settings', [SettingsController::class, 'index'])->name('settings.index');
    Route::get('/settings/properties', [PropertyManagementController::class, 'index'])->middleware('can:properties.view')->name('settings.properties.index');
    Route::post('/settings/properties', [PropertyManagementController::class, 'store'])->middleware('can:properties.create')->name('settings.properties.store');
    Route::get('/settings/properties/{property}/edit', [PropertyManagementController::class, 'edit'])->middleware('can:properties.update')->name('settings.properties.edit');
    Route::put('/settings/properties/{property}', [PropertyManagementController::class, 'update'])->middleware('can:properties.update')->name('settings.properties.update');
    Route::get('/settings/properties/{property}/access', [PropertyManagementController::class, 'access'])->middleware('can:members.view')->name('settings.properties.access');
    Route::put('/settings/properties/{property}/access', [PropertyManagementController::class, 'updateAccess'])->middleware('can:members.manage')->name('settings.properties.access.update');
    Route::get('/settings/organization', [OrganizationSettingsController::class, 'index'])->middleware('can:organization.view')->name('settings.organization.index');
    Route::put('/settings/organization', [OrganizationSettingsController::class, 'update'])->middleware('can:organization.update')->name('settings.organization.update');
    Route::get('/settings/subscription', [OrganizationSettingsController::class, 'subscription'])->middleware('can:organization.view')->name('settings.subscription');
    Route::get('/settings/members', [OrganizationMemberController::class, 'index'])->middleware('can:members.view')->name('settings.members.index');
    Route::get('/settings/members/{membership}/edit', [OrganizationMemberController::class, 'edit'])->middleware('can:members.manage')->name('settings.members.edit');
    Route::put('/settings/members/{membership}', [OrganizationMemberController::class, 'update'])->middleware('can:members.manage')->name('settings.members.update');
    Route::post('/settings/members/{membership}/owner', [OrganizationMemberController::class, 'grantOwner'])->middleware('can:members.manage')->name('settings.members.owner.grant');
    Route::delete('/settings/members/{membership}/owner', [OrganizationMemberController::class, 'removeOwner'])->middleware('can:members.manage')->name('settings.members.owner.remove');
    Route::get('/settings/audit', [OrganizationAuditController::class, 'index'])->middleware('can:audit.view')->name('settings.audit.index');
    Route::get('/settings/database/backup', [SettingsController::class, 'downloadDatabaseBackup'])->name('settings.database.backup');
    Route::get('/settings/database/backups/{filename}', [SettingsController::class, 'downloadExistingDatabaseBackup'])->where('filename', '[A-Za-z0-9._-]+')->name('settings.database.backups.download');
    Route::post('/settings/integrations/email', [SettingsController::class, 'updateEmail'])->name('settings.integrations.email');
    Route::post('/settings/integrations/email/test', [SettingsController::class, 'testEmail'])->name('settings.integrations.email.test');
    Route::post('/settings/integrations/whatsapp', [SettingsController::class, 'updateWhatsApp'])->name('settings.integrations.whatsapp');
    Route::post('/settings/integrations/api-tokens', [SettingsController::class, 'storeApiToken'])->middleware('feature:api_access')->name('settings.integrations.api-tokens.store');
    Route::post('/settings/integrations/api-tokens/{token}/revoke', [SettingsController::class, 'revokeApiToken'])->middleware('feature:api_access')->name('settings.integrations.api-tokens.revoke');
    Route::post('/settings/integrations/webhooks', [SettingsController::class, 'storeWebhook'])->name('settings.integrations.webhooks.store');
    Route::put('/settings/general', [SettingsController::class, 'updateGeneral'])->name('settings.general.update');
    Route::put('/settings/security', [SettingsController::class, 'updateSecurity'])->name('settings.security.update');
    Route::post('/settings/sources', [SettingsController::class, 'storeSource'])->name('settings.sources.store');
    Route::put('/settings/sources/{source}', [SettingsController::class, 'updateSource'])->name('settings.sources.update');
    Route::post('/settings/sources/{source}/toggle', [SettingsController::class, 'toggleSource'])->name('settings.sources.toggle');
    Route::delete('/settings/sources/{source}', [SettingsController::class, 'destroySource'])->name('settings.sources.destroy');
    Route::put('/settings/updates', [SettingsController::class, 'updateUpdates'])->name('settings.updates.update');
    Route::post('/settings/updates/check', [SettingsController::class, 'checkUpdates'])->name('settings.updates.check');
    Route::get('/notifications', [NotificationController::class, 'index'])->name('notifications.index');
    Route::post('/notifications/{notification}/read', [NotificationController::class, 'read'])->name('notifications.read');
    Route::post('/notifications/read-all', [NotificationController::class, 'readAll'])->name('notifications.read-all');
    Route::put('/notifications/preferences', [NotificationController::class, 'updatePreferences'])->name('notifications.preferences.update');
    Route::get('/announcements/dashboard', [AnnouncementController::class, 'dashboard'])->name('announcements.dashboard');
    Route::get('/announcements/{announcement}/statistics', [AnnouncementController::class, 'statistics'])->name('announcements.statistics');
    Route::get('/announcements/{announcement}/attachments/{attachment}', [AnnouncementController::class, 'download'])->name('announcements.attachments.download');
    Route::post('/announcements/{announcement}/publish', [AnnouncementController::class, 'publish'])->name('announcements.publish');
    Route::post('/announcements/{announcement}/archive', [AnnouncementController::class, 'archive'])->name('announcements.archive');
    Route::post('/announcements/{announcement}/read', [AnnouncementController::class, 'read'])->name('announcements.read');
    Route::post('/announcements/push-subscriptions', [AnnouncementController::class, 'subscribe'])->name('announcements.push-subscriptions.store');
    Route::delete('/announcements/push-subscriptions', [AnnouncementController::class, 'unsubscribe'])->name('announcements.push-subscriptions.destroy');
    Route::resource('announcements', AnnouncementController::class)->only(['index', 'create', 'store', 'show', 'edit', 'update']);
});
