@extends('layouts.app')
@section('content')
<x-page-header title="Expenses" subtitle="Submit expenditure for approval before it affects the finance ledger."><button type="button" class="ui-button ui-button--primary" data-modal-open="expense-form"><x-ui.icon name="plus" size="16" /> Submit expense</button></x-page-header>
@include('finance.partials.nav')
<section class="ui-card"><x-data.table caption="Hotel expenses"><thead><tr><th>Expense #</th><th>Date</th><th>Category</th><th>Payee</th><th>Department</th><th>Account</th><th>Amount</th><th>Reference</th><th>Status</th><th>Actions</th></tr></thead><tbody>
@forelse($expenses as $expense)
<tr><td><strong>{{ $expense->expense_number }}</strong>@if($expense->attachment_path)<a class="table-muted" href="{{ route('finance.expenses.attachment', $expense) }}">Attachment ({{ $expense->attachment_type ?: 'document' }})</a>@endif</td><td>{{ $expense->expense_date?->format('m/d/Y H:i') }}</td><td>{{ $expense->category?->name ?? 'Uncategorised' }}</td><td>{{ $expense->payee ?: '—' }}</td><td>{{ $expense->department?->name ?? '—' }}</td><td>{{ $expense->account?->name }}</td><td class="text-danger"><strong>{{ $formatter->format($expense->amount) }}</strong></td><td>{{ $expense->reference ?: '—' }}</td><td><x-ui.badge :variant="in_array($expense->status, ['paid','posted']) ? 'success' : ($expense->status === 'rejected' ? 'danger' : 'warning')">{{ str_replace('_',' ',ucfirst($expense->status)) }}</x-ui.badge></td><td><div class="row-actions">
@can('finance.expenses.approve') @if($expense->status === 'pending_approval')<form method="POST" action="{{ route('finance.expenses.action', [$expense, 'approve']) }}">@csrf<button class="ui-button ui-button--small ui-button--success" type="submit">Approve</button></form>@endif @endcan
@can('finance.expenses.submit') @if($expense->status === 'draft')<form method="POST" action="{{ route('finance.expenses.action', [$expense, 'submit']) }}">@csrf<button class="ui-button ui-button--small ui-button--primary" type="submit">Submit</button></form>@endif @endcan
@can('finance.expenses.reject') @if(in_array($expense->status, ['pending_approval','approved']))<form method="POST" action="{{ route('finance.expenses.action', [$expense, 'reject']) }}">@csrf<input name="reason" required placeholder="Reason"><button class="ui-button ui-button--small ui-button--danger" type="submit">Reject</button></form>@endif @endcan
@can('finance.expenses.pay') @if($expense->status === 'approved')<form method="POST" action="{{ route('finance.expenses.action', [$expense, 'pay']) }}">@csrf<button class="ui-button ui-button--small ui-button--primary" type="submit">Pay</button></form>@endif @endcan
@can('finance.expenses.reverse') @if(in_array($expense->status, ['paid','posted']))<form method="POST" action="{{ route('finance.expenses.action', [$expense, 'reverse']) }}">@csrf<input name="reason" required placeholder="Reason"><button class="ui-button ui-button--small ui-button--danger" type="submit">Reverse</button></form>@endif @endcan
</div></td></tr>
@empty <tr><td colspan="10"><div class="empty-state"><strong>No expenses recorded.</strong><span>New expenses require approval before they affect the finance ledger.</span></div></td></tr>
@endforelse
</tbody></x-data.table><x-data.pagination :paginator="$expenses" /></section>
<x-ui.modal id="expense-form" title="Submit expense" size="large"><form method="POST" action="{{ route('finance.expenses.store') }}" enctype="multipart/form-data">@csrf<div class="reservation-form__grid"><x-form.select name="account_id" label="Paid from" required><option value="">Select account</option>@foreach($accounts as $account)<option value="{{ $account->id }}">{{ $account->name }} ({{ $formatter->format($account->current_balance) }})</option>@endforeach</x-form.select><x-form.select name="category_id" label="Category"><option value="">Select category</option>@foreach($categories as $category)<option value="{{ $category->id }}">{{ $category->name }}</option>@endforeach</x-form.select><x-form.input name="amount" label="Amount" type="number" step="0.01" min="0.01" required /><x-form.input name="expense_date" label="Date / time" type="datetime-local" value="{{ now()->format('Y-m-d\TH:i') }}" required /><x-form.select name="department_id" label="Department"><option value="">No department</option>@foreach($departments as $department)<option value="{{ $department->id }}">{{ $department->name }}</option>@endforeach</x-form.select><x-form.input name="payee" label="Supplier / payee" /><x-form.select name="payment_method" label="Payment method"><option value="">Select method</option>@foreach(['cash','card','bank_transfer','mobile_money'] as $method)<option value="{{ $method }}">{{ str_replace('_',' ',ucfirst($method)) }}</option>@endforeach</x-form.select><x-form.select name="attachment_type" label="Attachment type"><option value="">No attachment</option>@foreach(['receipt','supplier_invoice','bank_proof','supporting_document'] as $type)<option value="{{ $type }}">{{ str_replace('_',' ',ucfirst($type)) }}</option>@endforeach</x-form.select><x-form.input name="reference" label="Reference" /><x-form.textarea name="description" label="Description" rows="3" class="form-field--full" required /><x-form.input name="attachment" type="file" label="Private receipt / document" class="form-field--full" /><label class="form-check"><input type="checkbox" name="save_as_draft" value="1"> Save as draft</label></div><div class="modal-form-footer"><button type="button" class="ui-button ui-button--secondary" data-modal-close>Cancel</button><button class="ui-button ui-button--primary" type="submit">Submit expense</button></div></form></x-ui.modal>
@endsection
