@extends('layouts.app')
@section('content')
<x-page-header title="Finance" subtitle="A clear view of the property’s money position, movement and attention items."><a class="ui-button ui-button--secondary" href="{{ route('payments.index') }}"><x-ui.icon name="card" size="16" /> Guest payments</a>@include('finance.partials.export', ['report' => 'cash-flow', 'label' => 'Export'])</x-page-header>
@include('finance.partials.nav')
@php($available = $accounts->sum('current_balance'))
<section class="finance-kpi-grid" aria-label="Finance summary">
    <x-kpi-card label="Available funds" :value="$formatter->format($available)" icon="currency" tone="success" context="All active accounts" :href="route('finance.accounts')" />
    <x-kpi-card label="Money in today" :value="$formatter->format($moneyIn)" icon="arrow-right" tone="info" context="Posted credits" :href="route('finance.transactions', ['direction' => 'credit', 'date' => 'today'])" />
    <x-kpi-card label="Money out today" :value="$formatter->format($moneyOut)" icon="arrow-left" tone="danger" context="Posted debits" :href="route('finance.transactions', ['direction' => 'debit', 'date' => 'today'])" />
    <x-kpi-card label="Net today" :value="$formatter->format($net)" icon="chart" tone="warning" context="Money in less out" />
    <x-kpi-card label="Outstanding balances" :value="$formatter->format($outstanding)" icon="alert" tone="danger" context="Guest balances" :href="route('reservations.index', ['balance' => 'outstanding'])" />
    <x-kpi-card label="Unreconciled items" :value="$pendingReconciliations" icon="check" tone="warning" context="Needs review" :href="route('finance.reconciliation')" />
    <x-kpi-card label="Pending approvals" :value="$pendingApprovals" icon="document" tone="info" context="Expenses awaiting action" :href="route('finance.expenses')" />
    <x-kpi-card label="Cash variance" :value="$cashVariance ? $formatter->format($cashVariance->variance) : '—'" icon="alert" tone="danger" context="Latest recorded close" :href="route('finance.petty-cash')" />
</section>
<div class="dashboard-grid dashboard-grid--main finance-overview-grid">
    <x-ui.card title="Cash flow" icon="chart"><x-slot:header><div class="finance-card-tools"><a class="finance-period {{ $period === 'today' ? 'is-active' : '' }}" href="{{ route('finance.overview', ['period' => 'today']) }}">Today</a><a class="finance-period {{ $period === '7' ? 'is-active' : '' }}" href="{{ route('finance.overview', ['period' => '7']) }}">7 days</a><a class="finance-period {{ $period === '30' ? 'is-active' : '' }}" href="{{ route('finance.overview', ['period' => '30']) }}">30 days</a><details class="finance-period finance-period--custom" @if($period === 'custom') open @endif><summary>Custom</summary><form method="GET" action="{{ route('finance.overview') }}"><input type="hidden" name="period" value="custom"><label>From <input type="date" name="from" value="{{ $flowFrom }}" required></label><label>To <input type="date" name="to" value="{{ $flowTo }}" required></label><button class="ui-button ui-button--small ui-button--primary" type="submit">Apply</button></form></details></div></x-slot:header>
        @php($flowMax = max(1, (float) $cashFlow->max(fn ($row) => max($row['money_in'], $row['money_out'], abs($row['net'])))))
        @php($hasFlow = $cashFlow->contains(fn ($flow) => $flow['money_in'] > 0 || $flow['money_out'] > 0))
        @if($hasFlow)<div class="finance-flow-chart" role="img" aria-label="Money in, money out and net cash flow for the selected period">
            @foreach($cashFlow as $flow)<div class="finance-flow-bar" title="{{ $flow['date'] }} · In {{ $formatter->format($flow['money_in']) }} · Out {{ $formatter->format($flow['money_out']) }}"><i class="finance-flow-bar__in" style="height: {{ max(3, ($flow['money_in'] / $flowMax) * 100) }}%"></i><i class="finance-flow-bar__out" style="height: {{ max(3, ($flow['money_out'] / $flowMax) * 100) }}%"></i></div>@endforeach
        </div>@else<div class="finance-chart-empty"><x-ui.icon name="chart" size="24" /><strong>No money movement in this period</strong><span>Posted credits and debits will appear here when recorded.</span></div>@endif
        <div class="finance-chart-legend"><span><i class="finance-legend-dot finance-legend-dot--in"></i>Money in</span><span><i class="finance-legend-dot finance-legend-dot--out"></i>Money out</span><span><i class="finance-legend-dot finance-legend-dot--net"></i>Net</span></div>
    </x-ui.card>
    <x-ui.card title="Where the money is" icon="building"><x-data.table class="finance-account-table" caption="Financial account balances"><thead><tr><th>Account</th><th>Type</th><th>Balance</th><th>Last movement</th><th>Reconciliation</th></tr></thead><tbody>@forelse($accounts as $account)<tr><td><strong>{{ $account->name }}</strong>@if($account->masked_account_number)<small class="table-muted">{{ $account->masked_account_number }}</small>@endif</td><td>{{ ['cash'=>'Cash','bank'=>'Bank','mobile_money'=>'Mobile Money','card_clearing'=>'Card Clearing','petty_cash'=>'Petty Cash','other'=>'Other'][$account->type] ?? ucfirst($account->type) }}</td><td><strong>{{ $formatter->format($account->current_balance) }}</strong><small class="table-muted">{{ $account->currency }}</small></td><td>{{ optional($lastMovements->get($account->id))->format('m/d/Y') ?: 'No movement' }}</td><td><x-ui.badge variant="success">Current</x-ui.badge></td></tr>@empty<tr><td colspan="5"><div class="empty-state"><x-ui.icon name="building" size="24" /><strong>No financial accounts configured.</strong><span>Accounts will appear here after setup.</span></div></td></tr>@endforelse</tbody></x-data.table></x-ui.card>
</div>
<div class="dashboard-grid dashboard-grid--secondary finance-overview-grid">
    <x-ui.card title="Recent ledger activity" icon="document"><x-data.table caption="Recent financial transactions"><thead><tr><th>Transaction</th><th>Description</th><th>Account</th><th>Movement</th></tr></thead><tbody>@forelse($recent as $transaction)<tr><td><strong>{{ $transaction->transaction_number }}</strong><small class="table-muted">{{ $transaction->transaction_date?->format('m/d/Y H:i') }}</small></td><td>{{ $transaction->description }}</td><td>{{ $transaction->account?->name ?: '—' }}</td><td class="{{ $transaction->direction === 'credit' ? 'text-success' : 'text-danger' }}">{{ $transaction->direction === 'credit' ? '+' : '-' }}{{ $formatter->format($transaction->amount) }}</td></tr>@empty<tr><td colspan="4"><div class="empty-state"><x-ui.icon name="document" size="24" /><strong>No posted ledger activity yet.</strong><span>Payments, expenses and transfers will appear here.</span></div></td></tr>@endforelse</tbody></x-data.table><a class="dashboard-widget-link finance-overview-link" href="{{ route('finance.transactions') }}">View all transactions <x-ui.icon name="arrow-right" size="14" /></a></x-ui.card>
    <x-ui.card title="Finance attention" icon="alert"><div class="finance-attention-list">@if($pendingReconciliations)<a href="{{ route('finance.reconciliation') }}" class="finance-attention-item"><x-ui.icon name="check" size="18" /><span><strong>{{ $pendingReconciliations }} unreconciled item(s)</strong><small>Review account reconciliation</small></span></a>@endif @if($pendingApprovals)<a href="{{ route('finance.expenses') }}" class="finance-attention-item"><x-ui.icon name="document" size="18" /><span><strong>{{ $pendingApprovals }} expense approval(s)</strong><small>Review pending expenses</small></span></a>@endif @if($cashVariance)<a href="{{ route('finance.petty-cash') }}" class="finance-attention-item"><x-ui.icon name="alert" size="18" /><span><strong>Cash variance {{ $formatter->format($cashVariance->variance) }}</strong><small>Latest petty-cash close</small></span></a>@endif @if(!$pendingReconciliations && !$pendingApprovals && !$cashVariance)<div class="empty-state empty-state--compact"><x-ui.icon name="check" size="24" /><strong>Nothing needs attention.</strong><span>Finance controls are up to date.</span></div>@endif</div></x-ui.card>
</div>
@endsection
