@extends('layouts.app')
@section('content')
<x-page-header title="Petty cash" subtitle="Control daily cash movements and close the physical balance with a visible variance."><div class="page-header__action-group"><a class="ui-button ui-button--secondary" href="{{ route('finance.expenses') }}">Record expense</a>@include('finance.partials.export', ['report' => 'petty-cash'])<button type="button" class="ui-button ui-button--primary" data-modal-open="cash-close-form">Close day</button></div></x-page-header>
@include('finance.partials.nav')
<div class="finance-context-strip"><span><x-ui.icon name="building" size="16" /> {{ $account->name }}</span><span>{{ $account->currency }}</span></div>
<x-kpi-grid :items="[['label' => 'Current balance', 'value' => $formatter->format($balance), 'icon' => 'currency', 'tone' => 'success'], ['label' => 'Added today', 'value' => $formatter->format($cashInToday), 'icon' => 'arrow-right', 'tone' => 'info'], ['label' => 'Spent today', 'value' => $formatter->format($cashOutToday), 'icon' => 'arrow-left', 'tone' => 'danger'], ['label' => 'Last close / variance', 'value' => $lastClose ? $formatter->format($lastClose->variance) : 'Not closed', 'icon' => 'check', 'tone' => $lastClose && abs((float) $lastClose->variance) < .01 ? 'success' : 'warning', 'context' => $lastClose?->close_date?->format('m/d/Y')]]" />
<div class="dashboard-grid dashboard-grid--main petty-cash-grid"><x-ui.card title="Petty cash ledger" icon="document"><x-data.table caption="Petty cash transactions"><thead><tr><th>Transaction</th><th>Date / time</th><th>Description</th><th>Money in</th><th>Money out</th><th>Balance</th><th>Reference</th></tr></thead><tbody>@php($running = (float) $balance + (float) $transactions->sum(fn ($row) => $row->direction === 'credit' ? $row->amount : -$row->amount))@forelse($transactions as $transaction)<tr><td><strong>{{ $transaction->transaction_number }}</strong></td><td>{{ $transaction->transaction_date?->format('m/d/Y H:i') }}</td><td>{{ $transaction->description ?: '—' }}</td><td class="text-success">{{ $transaction->direction === 'credit' ? $formatter->format($transaction->amount) : '—' }}</td><td class="text-danger">{{ $transaction->direction === 'debit' ? $formatter->format($transaction->amount) : '—' }}</td><td>{{ $formatter->format($running) }}</td><td>{{ $transaction->reference ?: '—' }}</td></tr>@php($running -= $transaction->direction === 'credit' ? $transaction->amount : -$transaction->amount)@empty<tr><td colspan="7"><div class="empty-state"><x-ui.icon name="document" size="24" /><strong>No petty cash movements.</strong><span>Added funds and recorded expenses will appear here.</span></div></td></tr>@endforelse</tbody></x-data.table><x-data.pagination :paginator="$transactions" /></x-ui.card>
<x-ui.card title="Daily cash close" icon="check"><div class="cash-close-summary"><div><span>Opening cash</span><strong>{{ $formatter->format($openingCash) }}</strong></div><div><span>Money in</span><strong class="text-success">{{ $formatter->format($cashInToday) }}</strong></div><div><span>Money out</span><strong class="text-danger">{{ $formatter->format($cashOutToday) }}</strong></div><div><span>Expected cash</span><strong>{{ $formatter->format($expectedCash) }}</strong></div></div><div class="cash-close-result"><div><span>Actual counted cash</span><strong>Enter at close</strong></div><div><span>Variance</span><strong class="text-muted">Calculated on close</strong></div></div><p class="form-help">Expected cash is calculated from the ledger. The close action records the actual count and the resulting variance.</p><button type="button" class="ui-button ui-button--primary" data-modal-open="cash-close-form">Close day</button></x-ui.card></div>
<section class="ui-card finance-recent-closes"><header class="ui-card__header"><div class="ui-card__heading"><x-ui.icon name="check" size="18" /><h2>Recent closes</h2></div></header><div class="ui-card__body"><x-data.table caption="Recent petty cash closes"><thead><tr><th>Date</th><th>Expected</th><th>Actual</th><th>Variance</th><th>Closed by</th><th>Status</th></tr></thead><tbody>@forelse($closes as $close)<tr><td>{{ $close->close_date?->format('m/d/Y') }}</td><td>{{ $formatter->format($close->expected_closing_cash) }}</td><td>{{ $formatter->format($close->actual_counted_cash) }}</td><td class="{{ abs((float) $close->variance) < .01 ? 'text-success' : 'text-danger' }}">{{ $formatter->format($close->variance) }}</td><td>{{ $close->closer?->display_name ?? 'System' }}</td><td><x-ui.badge :variant="abs((float) $close->variance) < .01 ? 'success' : 'warning'">{{ abs((float) $close->variance) < .01 ? 'Balanced' : 'Variance' }}</x-ui.badge></td></tr>@empty<tr><td colspan="6"><div class="empty-state empty-state--compact"><x-ui.icon name="check" size="22" /><strong>No daily closes recorded.</strong><span>Completed cash closes will be listed here.</span></div></td></tr>@endforelse</tbody></x-data.table></div></section>
<x-ui.modal id="cash-close-form" title="Close petty cash day"><form method="POST" action="{{ route('finance.petty-cash.close') }}"><div class="settings-form-grid">@csrf<x-form.input name="close_date" type="date" label="Close date" value="{{ now()->toDateString() }}" required /><x-form.input name="actual_counted_cash" type="number" step="0.01" min="0" label="Actual counted cash" required /><x-form.textarea name="notes" label="Notes" rows="3" fieldClass="form-field--full" /></div><div class="modal-form-footer"><button type="button" class="ui-button ui-button--secondary" data-modal-close>Cancel</button><button class="ui-button ui-button--primary" type="submit">Save close</button></div></form></x-ui.modal>
@endsection
