@extends('layouts.app')
@php($formatter = $formatter ?? app(\App\Support\CurrencyFormatter::class))
@section('content')
    <x-page-header title="Payments" subtitle="Cash, card and bank transfer transactions.">
        @can('print', \App\Models\Payment::class)<a class="ui-button ui-button--secondary" href="{{ route('payments.print', request()->query()) }}" target="_blank"><x-ui.icon name="print" size="16" /> Print</a>@endcan
        @can('export', \App\Models\Payment::class)<a class="ui-button ui-button--secondary" href="{{ route('payments.export', request()->query()) }}"><x-ui.icon name="download" size="16" /> Export CSV</a>@endcan
        @can('create', \App\Models\Payment::class)<button type="button" class="ui-button ui-button--primary" data-modal-open="payment-form"><x-ui.icon name="plus" size="16" /> New payment</button>@endcan
    </x-page-header>
    <x-kpi-grid :items="$kpis" />
    @if ($errors->any())<x-feedback.alert type="danger" class="page-feedback">{{ $errors->first() }}</x-feedback.alert>@endif
    <form class="filter-toolbar payment-filters" method="GET" action="{{ route('payments.index') }}"><x-form.input name="search" value="{{ request('search') }}" placeholder="Search" aria-label="Search payments" /><x-form.select name="status" aria-label="Filter by status"><option value="all">All</option>@foreach($statuses as $status)<option value="{{ $status->value }}" @selected(request('status','all')===$status->value)>{{ $status->label() }}</option>@endforeach</x-form.select><x-form.select name="method" aria-label="Filter by method"><option value="all">All methods</option>@foreach($paymentMethods as $method)<option value="{{ $method->code }}" @selected(request('method','all')===$method->code)>{{ $method->name }}</option>@endforeach</x-form.select><x-form.input name="from" type="date" value="{{ request('from') }}" aria-label="From date" /><x-form.input name="to" type="date" value="{{ request('to') }}" aria-label="To date" /><button class="ui-button ui-button--info" type="submit"><x-ui.icon name="filter" size="16" /> Filter</button><a class="ui-button ui-button--secondary" href="{{ route('payments.index') }}">Reset</a></form>
    <section class="ui-card payments-card"><x-data.table caption="Payments"><thead><tr><th>Invoice</th><th>Reservation</th><th>Guest</th><th>Amount</th><th>Method</th><th>Reference</th><th>Date</th><th>Status</th><th>Actions</th></tr></thead><tbody>
        @forelse($payments as $payment)
            <tr><td><a class="text-link reservation-code" href="{{ route('payments.index', ['invoice' => $payment->invoice?->id]) }}">{{ $payment->invoice_number }}</a></td><td><a class="text-link" href="{{ route('reservations.show', $payment->reservation) }}">{{ $payment->reservation?->code }}</a><small class="table-muted">Room {{ $payment->reservation?->room?->room_number ?? '—' }}</small></td><td><strong>{{ $payment->client?->full_name ?? '—' }}</strong><small class="table-muted">{{ $payment->client?->email }}</small></td><td><strong>{{ $formatter->format($payment->amount) }}</strong></td><td>{{ ucwords(str_replace('_', ' ', $payment->method)) }}</td><td>{{ $payment->reference ?? '—' }}</td><td>{{ $payment->transaction_date?->format('m/d/Y, h:i A') }}</td><td><x-ui.badge :variant="$payment->status->badgeVariant()">{{ $payment->status->label() }}</x-ui.badge></td><td><div class="row-actions"><a class="icon-button" aria-label="View invoice" data-tooltip="Invoice" href="{{ route('payments.index', ['invoice' => $payment->invoice?->id]) }}"><x-ui.icon name="document" size="17" /></a>@can('update', $payment)<a class="icon-button" aria-label="Edit payment" data-tooltip="Edit" href="{{ route('payments.index', ['edit' => $payment->id]) }}"><x-ui.icon name="edit" size="17" /></a>@endcan @can('void', $payment) @if(! in_array($payment->status, [\App\Enums\PaymentStatus::Voided, \App\Enums\PaymentStatus::Refunded], true))<button type="button" class="icon-button icon-button--danger" aria-label="Void payment" data-tooltip="Void" data-modal-open="void-payment-{{ $payment->id }}"><x-ui.icon name="trash" size="17" /></button>@endif @endcan @can('delete', $payment) @if($payment->status === \App\Enums\PaymentStatus::Pending)<form method="POST" action="{{ route('payments.destroy', $payment) }}" data-confirm="Delete this pending payment?">@csrf @method('DELETE')<button class="icon-button icon-button--danger" type="submit" aria-label="Delete payment" data-tooltip="Delete"><x-ui.icon name="trash" size="17" /></button></form>@endif @endcan</div></td></tr>
        @empty
            <tr><td colspan="9"><div class="empty-state"><x-ui.icon name="card" size="28" /><strong>{{ request()->hasAny(['search','status','method','from','to']) ? 'No payments match the selected filters.' : 'No payments recorded yet.' }}</strong><span>Record a payment against an active reservation to generate an invoice.</span></div></td></tr>
        @endforelse
    </tbody></x-data.table>@if($payments->hasPages())<div class="pagination-wrap">{{ $payments->links() }}</div>@endif</section>

    @can('create', \App\Models\Payment::class)
        <x-ui.modal id="payment-form" title="New payment" size="default" :open="$openNew">
            <form method="POST" action="{{ route('payments.store') }}" class="payment-form" data-payment-form data-submit-lock>@csrf
                <div class="payment-form__grid"><x-form.select name="reservation_id" label="Reservation" required data-payment-reservation><option value="">Select reservation</option>@foreach($reservationOptions as $reservation)<option value="{{ $reservation->id }}" data-total="{{ $reservation->total_amount }}" data-paid="{{ $reservation->paid_amount ?? 0 }}" data-balance="{{ $financials = max(0, (float)$reservation->total_amount-(float)($reservation->paid_amount??0)) }}" @selected(old('reservation_id', $selectedReservation?->id)===$reservation->id)>{{ $reservation->code }} · {{ $reservation->client?->full_name }} · Room {{ $reservation->room?->room_number }} ({{ $formatter->format($financials) }} due)</option>@endforeach</x-form.select><x-form.input name="amount" label="Amount" type="number" step="0.01" min="0.01" value="{{ old('amount', $selectedReservation ? max(0, (float)$selectedReservation->total_amount-(float)($selectedReservation->paid_amount??0)) : '') }}" required data-payment-amount /><x-form.select name="method" label="Method" required><option value="">Select method</option>@foreach($paymentMethods as $method)<option value="{{ $method->code }}" @selected(old('method')===$method->code)>{{ $method->name }}</option>@endforeach</x-form.select><x-form.input name="transaction_date" label="Transaction date" type="datetime-local" value="{{ old('transaction_date', now()->format('Y-m-d\\TH:i')) }}" required /><x-form.select name="status" label="Status"><option value="paid" @selected(old('status','paid')==='paid')>Paid</option><option value="pending" @selected(old('status')==='pending')>Pending</option></x-form.select><x-form.input name="reference" label="Reference" value="{{ old('reference') }}" placeholder="Generated if left blank" /><x-form.textarea name="notes" label="Notes" rows="3">{{ old('notes') }}</x-form.textarea></div>
                <div class="payment-summary" data-payment-summary><span>Reservation total <strong data-payment-total>—</strong></span><span>Already paid <strong data-payment-paid>—</strong></span><span>Balance after payment <strong data-payment-balance>—</strong></span></div><div class="modal-form-footer"><button type="button" class="ui-button ui-button--secondary" data-modal-close>Cancel</button><button type="submit" class="ui-button ui-button--primary"><x-ui.icon name="save" size="16" /> Record payment</button></div>
            </form>
        </x-ui.modal>
    @endcan
    @if($openPayment) @can('update', $openPayment)<x-ui.modal id="payment-edit" title="Edit payment"><form method="POST" action="{{ route('payments.update', $openPayment) }}" class="payment-form" data-submit-lock>@csrf @method('PUT')<div class="payment-form__grid"><x-form.input name="amount" label="Amount" type="number" step="0.01" min="0.01" value="{{ $openPayment->amount }}" :readonly="$openPayment->status !== \App\Enums\PaymentStatus::Pending" /><x-form.select name="method" label="Method" :disabled="$openPayment->status !== \App\Enums\PaymentStatus::Pending">@foreach($paymentMethods as $method)<option value="{{ $method->code }}" @selected($openPayment->method===$method->code)>{{ $method->name }}</option>@endforeach</x-form.select><x-form.input name="transaction_date" label="Transaction date" type="datetime-local" value="{{ $openPayment->transaction_date?->format('Y-m-d\\TH:i') }}" :readonly="$openPayment->status !== \App\Enums\PaymentStatus::Pending" /><x-form.select name="status" label="Status" :disabled="$openPayment->status !== \App\Enums\PaymentStatus::Pending"><option value="pending" @selected($openPayment->status === \App\Enums\PaymentStatus::Pending)>Pending</option><option value="paid">Paid</option></x-form.select><x-form.input name="reference" label="Reference" value="{{ $openPayment->reference }}" /><x-form.textarea name="notes" label="Notes" rows="3">{{ $openPayment->notes }}</x-form.textarea></div><div class="modal-form-footer"><button type="button" class="ui-button ui-button--secondary" data-modal-close>Cancel</button><button type="submit" class="ui-button ui-button--primary"><x-ui.icon name="save" size="16" /> Save changes</button></div></form></x-ui.modal>@endcan @endif
    @foreach($payments as $payment) @can('void', $payment) @if(! in_array($payment->status, [\App\Enums\PaymentStatus::Voided, \App\Enums\PaymentStatus::Refunded], true))<x-ui.modal id="void-payment-{{ $payment->id }}" title="Void payment"><p>Void <strong>{{ $payment->invoice_number }}</strong> for {{ $formatter->format($payment->amount) }}? This will restore the reservation balance and retain an audit trail.</p><form method="POST" action="{{ route('payments.void', $payment) }}" data-submit-lock>@csrf<x-form.textarea name="reason" label="Reason" rows="4" required placeholder="Explain why this payment is being voided."></x-form.textarea><div class="modal-form-footer"><button type="button" class="ui-button ui-button--secondary" data-modal-close>Keep payment</button><button type="submit" class="ui-button ui-button--danger"><x-ui.icon name="trash" size="16" /> Void payment</button></div></form></x-ui.modal>@endif @endcan @endforeach
    @if($invoice) @can('view', $invoice)<x-ui.modal id="invoice-preview" title="Invoice {{ $invoice->invoice_number }}" size="large" open><div class="invoice-preview">@include('invoices.partials.document', ['invoice' => $invoice, 'property' => $property, 'formatter' => $formatter])</div><div class="modal-form-footer"><button type="button" class="ui-button ui-button--secondary" data-modal-close>Close</button>@can('print', $invoice)<a class="ui-button ui-button--secondary" href="{{ route('invoices.print', $invoice) }}" target="_blank"><x-ui.icon name="print" size="16" /> Print</a>@endcan @can('download', $invoice)<a class="ui-button ui-button--primary" href="{{ route('invoices.download', $invoice) }}"><x-ui.icon name="download" size="16" /> Download PDF</a>@endcan</div></x-ui.modal>@endcan @endif
@endsection
