@extends('layouts.setup')
@section('content')
<main class="setup-shell">
    <aside class="setup-aside"><x-app-logo /><div class="setup-intro"><h1>HotelDesk setup</h1><p>Choose the operating mode, configure the administrator and prepare your hotel workspace.</p></div><ol class="setup-steps"><li class="is-complete"><span>✓</span><strong>Operating mode</strong></li><li class="{{ $step === 2 ? 'is-current' : '' }}"><span>2</span><strong>Administrator and currency</strong></li><li><span>3</span><strong>Finish</strong></li></ol></aside>
    <section class="setup-main">
        @if($step === 1)
            <div class="setup-panel"><h2>Choose your operating mode</h2><p class="setup-subtitle">Start with the deployment mode that matches how HotelDesk will be used.</p><form method="POST" action="{{ route('setup.operating-mode') }}" data-submit-lock>@csrf<div class="setup-mode-grid"><label class="setup-mode"><input type="radio" name="operating_mode" value="desktop" checked><span><strong>Desktop application</strong><small>Use HotelDesk on this property workstation.</small></span></label><label class="setup-mode"><input type="radio" name="operating_mode" value="web"><span><strong>Web application</strong><small>Run HotelDesk through a browser on your network.</small></span></label></div><div class="setup-actions"><span></span><button class="ui-button ui-button--primary" type="submit">Continue <x-ui.icon name="arrow-right" size="16" /></button></div></form></div>
        @else
            <div class="setup-panel"><h2>Configure administrator and currency</h2><p class="setup-subtitle">Currency is locked after setup. Later changes require a controlled conversion of existing amounts.</p><form method="POST" action="{{ route('setup.complete') }}" data-submit-lock>@csrf<input type="hidden" name="operating_mode" value="{{ $data['operating_mode'] ?? 'desktop' }}"><div class="setup-form-grid"><x-form.input name="property_name" label="Property name" value="{{ old('property_name', config('hotel.defaults.property_name')) }}" required class="form-field--full" /><x-form.input name="full_name" label="Administrator full name" value="{{ old('full_name') }}" required /><x-form.input name="property_email" type="email" label="Property email" value="{{ old('property_email') }}" /><x-form.input name="email" type="email" label="Administrator email" value="{{ old('email') }}" required /><x-form.input name="username" label="Username" value="{{ old('username') }}" required /><x-form.input name="property_phone" label="Property phone" value="{{ old('property_phone') }}" /><x-form.input name="password" type="password" label="Password" required help="Follow the configured password policy." /><x-form.input name="password_confirmation" type="password" label="Repeat password" required /><x-form.input name="property_address" label="Address" value="{{ old('property_address') }}" class="form-field--full" /><x-form.input name="property_city" label="City" value="{{ old('property_city') }}" /><x-form.input name="property_country" label="Country" value="{{ old('property_country') }}" /><x-form.select name="currency" label="Currency" required>@foreach($currencies as $currency)<option value="{{ $currency->code }}" @selected(old('currency', 'USD') === $currency->code)>{{ $currency->code }} · {{ $currency->name }}</option>@endforeach</x-form.select><x-form.select name="language" label="Language" required>@foreach($languages as $language)<option value="{{ $language->code }}" @selected(old('language', 'en') === $language->code)>{{ $language->name }}</option>@endforeach</x-form.select><x-form.select name="timezone" label="Property timezone" required>@foreach($timezones as $timezone)<option value="{{ $timezone }}" @selected(old('timezone', config('hotel.defaults.timezone')) === $timezone)>{{ $timezone }}</option>@endforeach</x-form.select></div><div class="setup-actions"><a class="ui-button ui-button--secondary" href="{{ route('setup.index') }}"> <x-ui.icon name="arrow-left" size="16" /> Back</a><button class="ui-button ui-button--primary" type="submit"><x-ui.icon name="settings" size="16" /> Install and configure</button></div></form></div>
        @endif
    </section>
</main>
@endsection
