@extends('layouts.platform')
@section('content')
<header class="platform-page-header"><div><h1>Platform Administrators</h1><p>Separate Lodgix control-plane identities. Customer organization roles are not shown here.</p></div></header>
<div class="platform-grid">
    <section class="platform-card"><header class="platform-card__header"><div><h2>Add administrator</h2><p>Passwords are hashed and never written to audit metadata.</p></div></header><div class="platform-card__body"><form method="POST" action="{{ route('platform.administrators.store') }}">
        @csrf
        <div class="platform-form-grid"><div class="form-field"><label class="form-label" for="name">Name</label><input class="form-control" id="name" name="name" required></div><div class="form-field"><label class="form-label" for="email">Email</label><input class="form-control" id="email" name="email" type="email" required></div><div class="form-field"><label class="form-label" for="password">Password</label><input class="form-control" id="password" name="password" type="password" minlength="12" required></div><div class="form-field"><label class="form-label" for="password_confirmation">Confirm password</label><input class="form-control" id="password_confirmation" name="password_confirmation" type="password" minlength="12" required></div></div><div class="platform-form-actions"><button class="ui-button ui-button--primary" type="submit">Create administrator</button></div>
    </form></div></section>
    <section class="platform-card"><header class="platform-card__header"><div><h2>Account safeguards</h2><p>High-privilege identity controls.</p></div></header><div class="platform-card__body"><div class="platform-note">Every Platform Administrator must enroll in mandatory 2FA before entering the control plane. You cannot disable your own account or the last active Platform Administrator. Administrator-assisted 2FA reset is intentionally not available; recovery is self-service with current password plus current authenticator or recovery code.</div></div></section>
</div>
<section class="platform-card" style="margin-top:18px"><header class="platform-card__header"><div><h2>Administrator accounts</h2><p>Disable accounts instead of deleting control-plane history.</p></div></header><div class="platform-table-wrap"><table class="platform-table"><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Status</th><th>2FA</th><th>Last login</th><th>Support sessions</th><th>Action</th></tr></thead><tbody>@forelse($administrators as $administrator)<tr><td><strong>{{ $administrator->name }}</strong><small>{{ $administrator->uuid }}</small></td><td>{{ $administrator->email }}</td><td>{{ str_replace('_', ' ', ucfirst($administrator->role)) }}</td><td><span class="ui-badge ui-badge--{{ $administrator->isActive() ? 'success' : 'neutral' }}">{{ ucfirst($administrator->status) }}</span></td><td><span class="ui-badge ui-badge--{{ $administrator->hasEnabledTwoFactorAuthentication() ? 'success' : 'warning' }}">{{ $administrator->hasEnabledTwoFactorAuthentication() ? 'Enabled' : 'Required' }}</span></td><td>{{ $administrator->last_login_at?->format('Y-m-d H:i') ?: 'Never' }}</td><td>{{ $administrator->support_sessions_count }}</td><td>@if($administrator->is(auth('platform')->user()))<span class="form-help">Current account</span>@else<form method="POST" action="{{ route('platform.administrators.status', $administrator) }}">@csrf @method('PATCH')<input type="hidden" name="status" value="{{ $administrator->isActive() ? 'disabled' : 'active' }}"><button class="ui-button ui-button--{{ $administrator->isActive() ? 'secondary' : 'primary' }} ui-button--compact" type="submit">{{ $administrator->isActive() ? 'Disable' : 'Activate' }}</button></form>@endif</td></tr>@empty<tr><td colspan="8"><div class="platform-empty"><strong>No Platform Administrators.</strong></div></td></tr>@endforelse</tbody></table></div><div class="platform-pagination">{{ $administrators->links() }}</div></section>
@endsection
