@php($paid = app(\App\Services\FinancialService::class)->paidAmount($reservation))
@php($roomCharges = $reservation->posRoomCharges()->where('status', 'active')->with('order.outlet')->latest('posted_at')->get())
@php($totalDue = app(\App\Services\FinancialService::class)->totalDue($reservation))
@php($balance = app(\App\Services\FinancialService::class)->balance($reservation))
<x-ui.modal id="reservation-details" title="Reservation details {{ $reservation->code }}" size="large" open>
    <div class="reservation-summary">
        <div><span class="reservation-code">{{ $reservation->code }}</span><x-ui.badge :variant="$reservation->status->badgeVariant()">{{ $reservation->status->label() }}</x-ui.badge><h2>{{ $reservation->client->full_name }}</h2><p><x-ui.icon name="bed" size="17" /> Room {{ $reservation->room->room_number }} · {{ $reservation->room->roomType?->name ?? 'Room' }} · {{ $reservation->source?->name ?? 'Direct' }}</p></div>
        <div class="financial-summary"><div><small>Total due</small><strong>{{ $formatter->format($totalDue) }}</strong></div><div><small>Paid</small><strong class="balance-paid">{{ $formatter->format($paid) }}</strong></div><div><small>Balance</small><strong class="{{ $balance > 0 ? 'balance-due' : 'balance-paid' }}">{{ $formatter->format($balance) }}</strong></div></div>
    </div>
    @if($roomCharges->isNotEmpty())<x-ui.card title="POS / Extra charges" icon="card"><x-data.table caption="POS extra charges"><thead><tr><th>Outlet</th><th>Order</th><th>Date</th><th>Amount</th></tr></thead><tbody>@foreach($roomCharges as $charge)<tr><td>{{ $charge->order?->outlet?->name ?? 'POS' }}</td><td><a class="text-link" href="{{ route('pos.orders.show', $charge->order) }}">{{ $charge->order?->order_number }}</a></td><td>{{ $charge->posted_at?->format('m/d/Y, h:i A') }}</td><td>{{ $formatter->format($charge->amount) }}</td></tr>@endforeach</tbody></x-data.table></x-ui.card>@endif
    <div class="details-card-grid">
        <x-ui.card title="Stay details" icon="calendar"><div class="detail-fields"><div><small>Check-in</small><span>{{ $reservation->check_in->format('m/d/Y, h:i A') }}</span></div><div><small>Check-out</small><span>{{ $reservation->check_out->format('m/d/Y, h:i A') }}</span></div><div><small>Nights</small><span>{{ $reservation->nights() }}</span></div><div><small>Guests</small><span>{{ $reservation->adults + $reservation->children }}</span></div><div><small>Adults</small><span>{{ $reservation->adults }}</span></div><div><small>Children</small><span>{{ $reservation->children }}</span></div><div><small>Nightly rate</small><span>{{ $formatter->format($reservation->nightly_rate) }}</span></div><div><small>Source</small><span>{{ $reservation->source?->name ?? '—' }}</span></div></div></x-ui.card>
        <x-ui.card title="Guest details" icon="users"><div class="detail-fields"><div><small>Name</small><span>{{ $reservation->client->full_name }}</span></div><div><small>Email</small><span>{{ $reservation->client->email }}</span></div><div><small>Phone</small><span>{{ $reservation->client->phone ?? '—' }}</span></div><div><small>Document</small><span>{{ trim(($reservation->client->document_type ?? '').' '.($reservation->client->document_number ?? '')) ?: '—' }}</span></div><div class="detail-field--full"><small>Address</small><span>{{ implode(', ', array_filter([$reservation->client->address, $reservation->client->city, $reservation->client->country])) ?: '—' }}</span></div><div class="detail-field--full"><small>Notes</small><span>{{ $reservation->client->notes ?: '—' }}</span></div></div></x-ui.card>
        <x-ui.card title="Room details" icon="building"><div class="detail-fields"><div><small>Room</small><span>{{ $reservation->room->room_number }}</span></div><div><small>Floor</small><span>{{ $reservation->room->floor?->name ?? $reservation->room->floor_id }}</span></div><div><small>Room type</small><span>{{ $reservation->room->roomType?->name ?? '—' }}</span></div><div><small>Category</small><span>{{ $reservation->room->category?->name ?? '—' }}</span></div><div><small>Capacity</small><span>{{ $reservation->room->capacity }}</span></div><div><small>Bed type</small><span>{{ $reservation->room->roomType?->bed_type ?? '—' }}</span></div><div><small>Room status</small><span><x-ui.badge variant="info">{{ $reservation->room->operational_status->label() }}</x-ui.badge></span></div><div><small>Housekeeping status</small><span><x-ui.badge variant="success">{{ $reservation->room->housekeeping_status->value }}</x-ui.badge></span></div><div><small>Base rate</small><span>{{ $formatter->format($reservation->room->base_rate) }}</span></div><div class="detail-field--full"><small>Amenities</small><span>{{ $reservation->room->roomType?->amenities?->pluck('name')->join(', ') ?: '—' }}</span></div></div></x-ui.card>
        <x-ui.card title="Booking information" icon="info"><div class="detail-fields"><div><small>Code</small><span>{{ $reservation->code }}</span></div><div><small>Status</small><span><x-ui.badge :variant="$reservation->status->badgeVariant()">{{ $reservation->status->label() }}</x-ui.badge></span></div><div><small>Created by</small><span>{{ $reservation->creator?->name ?? 'System' }}</span></div><div><small>Created at</small><span>{{ $reservation->created_at?->format('m/d/Y, h:i A') }}</span></div><div><small>Last updated</small><span>{{ $reservation->updated_at?->format('m/d/Y, h:i A') }}</span></div><div class="detail-field--full"><small>Notes</small><span>{{ $reservation->notes ?: '—' }}</span></div>@if($reservation->cancellation_reason)<div class="detail-field--full"><small>Cancellation reason</small><span>{{ $reservation->cancellation_reason }}</span></div>@endif</div></x-ui.card>
    </div>
    <div class="details-footer">
        <form method="POST" action="{{ route('reservations.destroy', $reservation) }}" data-confirm="Remove this reservation from the active list?">@csrf @method('DELETE')<button class="text-button text-button--danger" type="submit"><x-ui.icon name="trash" size="16" /> Delete</button></form>
        <div class="details-footer__actions"><button type="button" class="ui-button ui-button--secondary" data-modal-close>Close</button>@can('update', $reservation)<a class="ui-button ui-button--secondary" href="{{ route('reservations.edit', $reservation) }}"><x-ui.icon name="edit" size="16" /> Edit</a>@endcan @can('create', \App\Models\Payment::class) @if($balance > 0)<a class="ui-button ui-button--info" href="{{ route('payments.index', ['new' => 1, 'reservation' => $reservation->id]) }}"><x-ui.icon name="card" size="16" /> Add payment</a>@endif @endcan @can('noShow', $reservation) @if($reservation->status === \App\Enums\ReservationStatus::Confirmed)<form method="POST" action="{{ route('reservations.no-show', $reservation) }}">@csrf<button class="ui-button ui-button--secondary" type="submit">Mark no-show</button></form>@endif @endcan @can('cancel', $reservation) @if(in_array($reservation->status, [\App\Enums\ReservationStatus::Pending, \App\Enums\ReservationStatus::Confirmed], true))<button type="button" class="ui-button ui-button--danger" data-modal-open="cancel-reservation"><x-ui.icon name="plus" size="16" /> Cancel reservation</button>@endif @endcan @can('checkIn', $reservation) @if($reservation->status === \App\Enums\ReservationStatus::Confirmed)<form method="POST" action="{{ route('reservations.check-in', $reservation) }}">@csrf<button class="ui-button ui-button--success" type="submit"><x-ui.icon name="check" size="16" /> Check in</button></form>@endif @endcan @can('checkOut', $reservation) @if($reservation->status === \App\Enums\ReservationStatus::CheckedIn)<form method="POST" action="{{ route('reservations.check-out', $reservation) }}">@csrf<button class="ui-button ui-button--success" type="submit"><x-ui.icon name="arrow-right" size="16" /> Check out</button></form>@endif @endcan</div>
    </div>
</x-ui.modal>
@can('cancel', $reservation)<x-ui.modal id="cancel-reservation" title="Cancel reservation"><form method="POST" action="{{ route('reservations.cancel', $reservation) }}"><div class="form-field"><label for="cancellation_reason">Reason</label><textarea class="form-control" id="cancellation_reason" name="cancellation_reason" rows="4" placeholder="Optional reason"></textarea></div><div class="modal-form-footer"><button type="button" class="ui-button ui-button--secondary" data-modal-close>Keep reservation</button><button type="submit" class="ui-button ui-button--danger">Cancel reservation</button></div>@csrf</form></x-ui.modal>@endcan
