@extends('layouts.app')
@section('content')
<x-page-header title="Notifications" subtitle="Operational, financial and integration activity for your role." />
<x-ui.card title="Notification center" icon="bell">
    <x-slot:header><form method="POST" action="{{ route('notifications.read-all') }}">@csrf<button class="ui-button ui-button--secondary" type="submit">Mark all read</button></form></x-slot:header>
    @php($preferences = auth()->user()->notificationPreferences()->first())
    <form method="POST" action="{{ route('notifications.preferences.update') }}" class="notification-preferences">@csrf @method('PUT')<strong>My delivery preferences</strong><label class="check-field"><input type="checkbox" name="channels[]" value="in_app" @checked(in_array('in_app', $preferences?->channels ?? ['in_app'], true))> In-app</label><label class="check-field"><input type="checkbox" name="channels[]" value="email" @checked(in_array('email', $preferences?->channels ?? [], true))> Email</label><label class="check-field"><input type="checkbox" name="channels[]" value="whatsapp" @checked(in_array('whatsapp', $preferences?->channels ?? [], true))> WhatsApp</label><button class="ui-button ui-button--secondary" type="submit">Save preferences</button></form>
    <div class="notification-filters"><a class="{{ $filter === '' ? 'is-active' : '' }}" href="{{ route('notifications.index') }}">All</a><a class="{{ $filter === 'unread' ? 'is-active' : '' }}" href="{{ route('notifications.index', ['filter' => 'unread']) }}">Unread</a><a class="{{ $filter === 'operational' ? 'is-active' : '' }}" href="{{ route('notifications.index', ['filter' => 'operational']) }}">Operational</a><a class="{{ $filter === 'financial' ? 'is-active' : '' }}" href="{{ route('notifications.index', ['filter' => 'financial']) }}">Financial</a></div>
    <div class="notification-list">@forelse($notifications as $notification)<article class="notification-item {{ $notification->read_at ? '' : 'is-unread' }}"><div><strong>{{ $notification->data['title'] ?? 'Notification' }}</strong><p>{{ $notification->data['message'] ?? '' }}</p><small>{{ $notification->created_at->diffForHumans() }}</small></div><div class="notification-item__actions">@if(!$notification->read_at)<form method="POST" action="{{ route('notifications.read', $notification->id) }}">@csrf<button class="ui-button ui-button--secondary" type="submit">Mark read</button></form>@endif @if(!empty($notification->data['action_url']))<a class="ui-button ui-button--info" href="{{ $notification->data['action_url'] }}">Open</a>@endif</div></article>@empty<p class="settings-lead">No notifications yet.</p>@endforelse</div>
    {{ $notifications->links() }}
</x-ui.card>
@endsection
