@extends('layouts.platform')

@section('content')
<header class="platform-page-header"><div><h1>Platform overview</h1><p>Real-time metadata for the Lodgix customer platform.</p></div><div class="platform-actions"><a class="ui-button ui-button--secondary" href="{{ route('platform.health') }}">System health</a><a class="ui-button ui-button--primary" href="{{ route('platform.organizations') }}">View organizations</a></div></header>
<section class="platform-kpis" aria-label="Platform metrics">
    @foreach([['Organizations', $metrics['organizations'], $metrics['active_organizations'].' active'], ['Properties', $metrics['properties'], 'Across all organizations'], ['Customer users', $metrics['customer_users'], 'Organization identities'], ['Subscriptions', $metrics['subscriptions'], $metrics['active_subscriptions'].' active · '.$metrics['trialing_subscriptions'].' trialing']] as [$label, $value, $hint])
        <article class="platform-kpi"><div class="platform-kpi__label">{{ $label }}</div><div class="platform-kpi__value">{{ number_format($value) }}</div><div class="platform-kpi__hint">{{ $hint }}</div></article>
    @endforeach
</section>
<div class="platform-grid">
    <section class="platform-card"><header class="platform-card__header"><div><h2>Recent organizations</h2><p>Newest customer accounts recorded by the platform.</p></div><a class="text-link" href="{{ route('platform.organizations') }}">View all</a></header><div class="platform-table-wrap"><table class="platform-table"><thead><tr><th>Organization</th><th>Status</th><th>Properties</th><th>Created</th></tr></thead><tbody>@forelse($organizations as $organization)<tr><td><a class="text-link" href="{{ route('platform.organizations.show', $organization) }}"><strong>{{ $organization->name }}</strong></a><small>{{ $organization->uuid }}</small></td><td><span class="ui-badge ui-badge--{{ $organization->status === 'active' ? 'success' : 'warning' }}">{{ str_replace('_', ' ', ucfirst($organization->status)) }}</span></td><td>{{ $organization->properties_count }}</td><td>{{ $organization->created_at?->format('Y-m-d') }}</td></tr>@empty<tr><td colspan="4"><div class="platform-empty"><strong>No organizations yet.</strong><span>Customer accounts will appear here when created.</span></div></td></tr>@endforelse</tbody></table></div></section>
    <section class="platform-card"><header class="platform-card__header"><div><h2>System health</h2><p>Safe checks from the current application.</p></div><a class="text-link" href="{{ route('platform.health') }}">Details</a></header><div class="platform-card__body"><div class="platform-status-list">@foreach($health as $key => $check)<div class="platform-status-row"><div class="platform-status-row__copy"><strong>{{ str_replace('_', ' ', ucfirst($key)) }}</strong><span>{{ $check['detail'] }}</span></div><span class="ui-badge ui-badge--{{ $check['status'] === 'healthy' ? 'success' : ($check['status'] === 'warning' ? 'warning' : 'danger') }}">{{ $check['label'] }}</span></div>@endforeach</div></div></section>
</div>
<section class="platform-card" style="margin-top:18px"><header class="platform-card__header"><div><h2>Recent platform activity</h2><p>Control-plane events only. Customer audit remains in the organization workspace.</p></div><a class="text-link" href="{{ route('platform.audit') }}">Open audit</a></header><div class="platform-table-wrap"><table class="platform-table"><thead><tr><th>Action</th><th>Administrator</th><th>Target</th><th>Time</th></tr></thead><tbody>@forelse($activity as $event)<tr><td><strong>{{ str_replace('.', ' · ', $event->action) }}</strong></td><td>{{ $event->administrator?->name ?? 'System' }}</td><td>{{ class_basename($event->target_type ?? 'Platform') }} {{ $event->target_id }}</td><td>{{ $event->created_at?->diffForHumans() }}</td></tr>@empty<tr><td colspan="4"><div class="platform-empty"><strong>No platform activity yet.</strong><span>Administrative events will be retained here.</span></div></td></tr>@endforelse</tbody></table></div></section>
@endsection
